<?php
/**
 * ConvertApi
 * PHP version 8.1
 *
 * @category Class
 * @package  StripyHorse
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ben@stripyhorse.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace StripyHorse\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use StripyHorse\ApiException;
use StripyHorse\Configuration;
use StripyHorse\FormDataProcessor;
use StripyHorse\HeaderSelector;
use StripyHorse\ObjectSerializer;

/**
 * ConvertApi Class Doc Comment
 *
 * @category Class
 * @package  StripyHorse
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ConvertApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'convertBatch' => [
            'multipart/form-data',
        ],
        'convertDocument' => [
            'multipart/form-data',
        ],
        'convertHtml' => [
            'application/json',
        ],
        'convertZplToHtml' => [
            'application/json',
        ],
        'rasterizeUnicode' => [
            'application/json',
        ],
        'stampZpl' => [
            'application/json',
        ],
        'voidZpl' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation convertBatch
     *
     * Convert many documents in one request, results streamed
     *
     * @param  \SplFileObject[] $files files (required)
     * @param  bool|null $barcode_aware barcode_aware (optional)
     * @param  string|null $compression compression (optional)
     * @param  int|null $dpmm dpmm (optional)
     * @param  float|null $height_mm height_mm (optional)
     * @param  string|null $preset preset (optional)
     * @param  int|null $rotation rotation (optional)
     * @param  string|null $scale scale (optional)
     * @param  int|null $threshold threshold (optional)
     * @param  float|null $width_mm width_mm (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['convertBatch'] to see the possible values for this operation
     *
     * @throws \StripyHorse\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function convertBatch($files, $barcode_aware = null, $compression = null, $dpmm = null, $height_mm = null, $preset = null, $rotation = null, $scale = null, $threshold = null, $width_mm = null, string $contentType = self::contentTypes['convertBatch'][0])
    {
        $this->convertBatchWithHttpInfo($files, $barcode_aware, $compression, $dpmm, $height_mm, $preset, $rotation, $scale, $threshold, $width_mm, $contentType);
    }

    /**
     * Operation convertBatchWithHttpInfo
     *
     * Convert many documents in one request, results streamed
     *
     * @param  \SplFileObject[] $files (required)
     * @param  bool|null $barcode_aware (optional)
     * @param  string|null $compression (optional)
     * @param  int|null $dpmm (optional)
     * @param  float|null $height_mm (optional)
     * @param  string|null $preset (optional)
     * @param  int|null $rotation (optional)
     * @param  string|null $scale (optional)
     * @param  int|null $threshold (optional)
     * @param  float|null $width_mm (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['convertBatch'] to see the possible values for this operation
     *
     * @throws \StripyHorse\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function convertBatchWithHttpInfo($files, $barcode_aware = null, $compression = null, $dpmm = null, $height_mm = null, $preset = null, $rotation = null, $scale = null, $threshold = null, $width_mm = null, string $contentType = self::contentTypes['convertBatch'][0])
    {
        $request = $this->convertBatchRequest($files, $barcode_aware, $compression, $dpmm, $height_mm, $preset, $rotation, $scale, $threshold, $width_mm, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\StripyHorse\Model\ErrorModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation convertBatchAsync
     *
     * Convert many documents in one request, results streamed
     *
     * @param  \SplFileObject[] $files (required)
     * @param  bool|null $barcode_aware (optional)
     * @param  string|null $compression (optional)
     * @param  int|null $dpmm (optional)
     * @param  float|null $height_mm (optional)
     * @param  string|null $preset (optional)
     * @param  int|null $rotation (optional)
     * @param  string|null $scale (optional)
     * @param  int|null $threshold (optional)
     * @param  float|null $width_mm (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['convertBatch'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function convertBatchAsync($files, $barcode_aware = null, $compression = null, $dpmm = null, $height_mm = null, $preset = null, $rotation = null, $scale = null, $threshold = null, $width_mm = null, string $contentType = self::contentTypes['convertBatch'][0])
    {
        return $this->convertBatchAsyncWithHttpInfo($files, $barcode_aware, $compression, $dpmm, $height_mm, $preset, $rotation, $scale, $threshold, $width_mm, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation convertBatchAsyncWithHttpInfo
     *
     * Convert many documents in one request, results streamed
     *
     * @param  \SplFileObject[] $files (required)
     * @param  bool|null $barcode_aware (optional)
     * @param  string|null $compression (optional)
     * @param  int|null $dpmm (optional)
     * @param  float|null $height_mm (optional)
     * @param  string|null $preset (optional)
     * @param  int|null $rotation (optional)
     * @param  string|null $scale (optional)
     * @param  int|null $threshold (optional)
     * @param  float|null $width_mm (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['convertBatch'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function convertBatchAsyncWithHttpInfo($files, $barcode_aware = null, $compression = null, $dpmm = null, $height_mm = null, $preset = null, $rotation = null, $scale = null, $threshold = null, $width_mm = null, string $contentType = self::contentTypes['convertBatch'][0])
    {
        $returnType = '';
        $request = $this->convertBatchRequest($files, $barcode_aware, $compression, $dpmm, $height_mm, $preset, $rotation, $scale, $threshold, $width_mm, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'convertBatch'
     *
     * @param  \SplFileObject[] $files (required)
     * @param  bool|null $barcode_aware (optional)
     * @param  string|null $compression (optional)
     * @param  int|null $dpmm (optional)
     * @param  float|null $height_mm (optional)
     * @param  string|null $preset (optional)
     * @param  int|null $rotation (optional)
     * @param  string|null $scale (optional)
     * @param  int|null $threshold (optional)
     * @param  float|null $width_mm (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['convertBatch'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function convertBatchRequest($files, $barcode_aware = null, $compression = null, $dpmm = null, $height_mm = null, $preset = null, $rotation = null, $scale = null, $threshold = null, $width_mm = null, string $contentType = self::contentTypes['convertBatch'][0])
    {

        // verify the required parameter 'files' is set
        if ($files === null || (is_array($files) && count($files) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $files when calling convertBatch'
            );
        }











        $resourcePath = '/v1/convert/batch';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // form params
        $formDataProcessor = new FormDataProcessor();

        $formData = $formDataProcessor->prepare([
            'barcodeAware' => $barcode_aware,
            'compression' => $compression,
            'dpmm' => $dpmm,
            'files' => $files,
            'heightMm' => $height_mm,
            'preset' => $preset,
            'rotation' => $rotation,
            'scale' => $scale,
            'threshold' => $threshold,
            'widthMm' => $width_mm,
        ]);

        $formParams = $formDataProcessor->flatten($formData);
        $multipart = $formDataProcessor->has_file;

        $multipart = true;
        $headers = $this->headerSelector->selectHeaders(
            ['application/problem+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Api-Key');
        if ($apiKey !== null) {
            $headers['X-Api-Key'] = $apiKey;
        }
        // this endpoint requires Bearer (sh_live_…) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation convertDocument
     *
     * Convert a PDF or image to ZPL
     *
     * @param  \SplFileObject $file PDF, PNG, GIF or JPEG (required)
     * @param  bool|null $barcode_aware EXPERIMENTAL: re-emit decodable barcodes as native ^BC/^BQ fields, verified by a decode round trip with automatic fallback to plain rasterization (optional)
     * @param  string|null $compression acs (default) or z64 (zlib+base64, smaller payloads) (optional)
     * @param  int|null $dpmm dpmm (optional)
     * @param  float|null $height_mm height_mm (optional)
     * @param  string|null $preset preset (optional)
     * @param  int|null $rotation rotation (optional)
     * @param  string|null $scale cover (fit), fill (stretch) or none (optional)
     * @param  int|null $threshold threshold (optional)
     * @param  float|null $width_mm width_mm (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['convertDocument'] to see the possible values for this operation
     *
     * @throws \StripyHorse\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \StripyHorse\Model\ConvertOutputBody|\StripyHorse\Model\ErrorModel
     */
    public function convertDocument($file, $barcode_aware = null, $compression = null, $dpmm = null, $height_mm = null, $preset = null, $rotation = null, $scale = null, $threshold = null, $width_mm = null, string $contentType = self::contentTypes['convertDocument'][0])
    {
        list($response) = $this->convertDocumentWithHttpInfo($file, $barcode_aware, $compression, $dpmm, $height_mm, $preset, $rotation, $scale, $threshold, $width_mm, $contentType);
        return $response;
    }

    /**
     * Operation convertDocumentWithHttpInfo
     *
     * Convert a PDF or image to ZPL
     *
     * @param  \SplFileObject $file PDF, PNG, GIF or JPEG (required)
     * @param  bool|null $barcode_aware EXPERIMENTAL: re-emit decodable barcodes as native ^BC/^BQ fields, verified by a decode round trip with automatic fallback to plain rasterization (optional)
     * @param  string|null $compression acs (default) or z64 (zlib+base64, smaller payloads) (optional)
     * @param  int|null $dpmm (optional)
     * @param  float|null $height_mm (optional)
     * @param  string|null $preset (optional)
     * @param  int|null $rotation (optional)
     * @param  string|null $scale cover (fit), fill (stretch) or none (optional)
     * @param  int|null $threshold (optional)
     * @param  float|null $width_mm (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['convertDocument'] to see the possible values for this operation
     *
     * @throws \StripyHorse\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \StripyHorse\Model\ConvertOutputBody|\StripyHorse\Model\ErrorModel, HTTP status code, HTTP response headers (array of strings)
     */
    public function convertDocumentWithHttpInfo($file, $barcode_aware = null, $compression = null, $dpmm = null, $height_mm = null, $preset = null, $rotation = null, $scale = null, $threshold = null, $width_mm = null, string $contentType = self::contentTypes['convertDocument'][0])
    {
        $request = $this->convertDocumentRequest($file, $barcode_aware, $compression, $dpmm, $height_mm, $preset, $rotation, $scale, $threshold, $width_mm, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\StripyHorse\Model\ConvertOutputBody',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\StripyHorse\Model\ErrorModel',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\StripyHorse\Model\ConvertOutputBody',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\StripyHorse\Model\ConvertOutputBody',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\StripyHorse\Model\ErrorModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation convertDocumentAsync
     *
     * Convert a PDF or image to ZPL
     *
     * @param  \SplFileObject $file PDF, PNG, GIF or JPEG (required)
     * @param  bool|null $barcode_aware EXPERIMENTAL: re-emit decodable barcodes as native ^BC/^BQ fields, verified by a decode round trip with automatic fallback to plain rasterization (optional)
     * @param  string|null $compression acs (default) or z64 (zlib+base64, smaller payloads) (optional)
     * @param  int|null $dpmm (optional)
     * @param  float|null $height_mm (optional)
     * @param  string|null $preset (optional)
     * @param  int|null $rotation (optional)
     * @param  string|null $scale cover (fit), fill (stretch) or none (optional)
     * @param  int|null $threshold (optional)
     * @param  float|null $width_mm (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['convertDocument'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function convertDocumentAsync($file, $barcode_aware = null, $compression = null, $dpmm = null, $height_mm = null, $preset = null, $rotation = null, $scale = null, $threshold = null, $width_mm = null, string $contentType = self::contentTypes['convertDocument'][0])
    {
        return $this->convertDocumentAsyncWithHttpInfo($file, $barcode_aware, $compression, $dpmm, $height_mm, $preset, $rotation, $scale, $threshold, $width_mm, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation convertDocumentAsyncWithHttpInfo
     *
     * Convert a PDF or image to ZPL
     *
     * @param  \SplFileObject $file PDF, PNG, GIF or JPEG (required)
     * @param  bool|null $barcode_aware EXPERIMENTAL: re-emit decodable barcodes as native ^BC/^BQ fields, verified by a decode round trip with automatic fallback to plain rasterization (optional)
     * @param  string|null $compression acs (default) or z64 (zlib+base64, smaller payloads) (optional)
     * @param  int|null $dpmm (optional)
     * @param  float|null $height_mm (optional)
     * @param  string|null $preset (optional)
     * @param  int|null $rotation (optional)
     * @param  string|null $scale cover (fit), fill (stretch) or none (optional)
     * @param  int|null $threshold (optional)
     * @param  float|null $width_mm (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['convertDocument'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function convertDocumentAsyncWithHttpInfo($file, $barcode_aware = null, $compression = null, $dpmm = null, $height_mm = null, $preset = null, $rotation = null, $scale = null, $threshold = null, $width_mm = null, string $contentType = self::contentTypes['convertDocument'][0])
    {
        $returnType = '\StripyHorse\Model\ConvertOutputBody';
        $request = $this->convertDocumentRequest($file, $barcode_aware, $compression, $dpmm, $height_mm, $preset, $rotation, $scale, $threshold, $width_mm, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'convertDocument'
     *
     * @param  \SplFileObject $file PDF, PNG, GIF or JPEG (required)
     * @param  bool|null $barcode_aware EXPERIMENTAL: re-emit decodable barcodes as native ^BC/^BQ fields, verified by a decode round trip with automatic fallback to plain rasterization (optional)
     * @param  string|null $compression acs (default) or z64 (zlib+base64, smaller payloads) (optional)
     * @param  int|null $dpmm (optional)
     * @param  float|null $height_mm (optional)
     * @param  string|null $preset (optional)
     * @param  int|null $rotation (optional)
     * @param  string|null $scale cover (fit), fill (stretch) or none (optional)
     * @param  int|null $threshold (optional)
     * @param  float|null $width_mm (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['convertDocument'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function convertDocumentRequest($file, $barcode_aware = null, $compression = null, $dpmm = null, $height_mm = null, $preset = null, $rotation = null, $scale = null, $threshold = null, $width_mm = null, string $contentType = self::contentTypes['convertDocument'][0])
    {

        // verify the required parameter 'file' is set
        if ($file === null || (is_array($file) && count($file) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $file when calling convertDocument'
            );
        }











        $resourcePath = '/v1/convert';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // form params
        $formDataProcessor = new FormDataProcessor();

        $formData = $formDataProcessor->prepare([
            'barcodeAware' => $barcode_aware,
            'compression' => $compression,
            'dpmm' => $dpmm,
            'file' => $file,
            'heightMm' => $height_mm,
            'preset' => $preset,
            'rotation' => $rotation,
            'scale' => $scale,
            'threshold' => $threshold,
            'widthMm' => $width_mm,
        ]);

        $formParams = $formDataProcessor->flatten($formData);
        $multipart = $formDataProcessor->has_file;

        $multipart = true;
        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Api-Key');
        if ($apiKey !== null) {
            $headers['X-Api-Key'] = $apiKey;
        }
        // this endpoint requires Bearer (sh_live_…) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation convertHtml
     *
     * Convert an HTML label design to ZPL
     *
     * @param  \StripyHorse\Model\HtmlInputBody $html_input_body html_input_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['convertHtml'] to see the possible values for this operation
     *
     * @throws \StripyHorse\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \StripyHorse\Model\HtmlOutputBody|\StripyHorse\Model\ErrorModel
     */
    public function convertHtml($html_input_body, string $contentType = self::contentTypes['convertHtml'][0])
    {
        list($response) = $this->convertHtmlWithHttpInfo($html_input_body, $contentType);
        return $response;
    }

    /**
     * Operation convertHtmlWithHttpInfo
     *
     * Convert an HTML label design to ZPL
     *
     * @param  \StripyHorse\Model\HtmlInputBody $html_input_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['convertHtml'] to see the possible values for this operation
     *
     * @throws \StripyHorse\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \StripyHorse\Model\HtmlOutputBody|\StripyHorse\Model\ErrorModel, HTTP status code, HTTP response headers (array of strings)
     */
    public function convertHtmlWithHttpInfo($html_input_body, string $contentType = self::contentTypes['convertHtml'][0])
    {
        $request = $this->convertHtmlRequest($html_input_body, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\StripyHorse\Model\HtmlOutputBody',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\StripyHorse\Model\ErrorModel',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\StripyHorse\Model\HtmlOutputBody',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\StripyHorse\Model\HtmlOutputBody',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\StripyHorse\Model\ErrorModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation convertHtmlAsync
     *
     * Convert an HTML label design to ZPL
     *
     * @param  \StripyHorse\Model\HtmlInputBody $html_input_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['convertHtml'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function convertHtmlAsync($html_input_body, string $contentType = self::contentTypes['convertHtml'][0])
    {
        return $this->convertHtmlAsyncWithHttpInfo($html_input_body, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation convertHtmlAsyncWithHttpInfo
     *
     * Convert an HTML label design to ZPL
     *
     * @param  \StripyHorse\Model\HtmlInputBody $html_input_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['convertHtml'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function convertHtmlAsyncWithHttpInfo($html_input_body, string $contentType = self::contentTypes['convertHtml'][0])
    {
        $returnType = '\StripyHorse\Model\HtmlOutputBody';
        $request = $this->convertHtmlRequest($html_input_body, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'convertHtml'
     *
     * @param  \StripyHorse\Model\HtmlInputBody $html_input_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['convertHtml'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function convertHtmlRequest($html_input_body, string $contentType = self::contentTypes['convertHtml'][0])
    {

        // verify the required parameter 'html_input_body' is set
        if ($html_input_body === null || (is_array($html_input_body) && count($html_input_body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $html_input_body when calling convertHtml'
            );
        }


        $resourcePath = '/v1/convert/html';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($html_input_body)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($html_input_body));
            } else {
                $httpBody = $html_input_body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Api-Key');
        if ($apiKey !== null) {
            $headers['X-Api-Key'] = $apiKey;
        }
        // this endpoint requires Bearer (sh_live_…) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation convertZplToHtml
     *
     * Decompile ZPL into editable HTML
     *
     * @param  \StripyHorse\Model\ZplHTMLInputBody $zpl_html_input_body zpl_html_input_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['convertZplToHtml'] to see the possible values for this operation
     *
     * @throws \StripyHorse\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \StripyHorse\Model\ZplHTMLOutputBody|\StripyHorse\Model\ErrorModel
     */
    public function convertZplToHtml($zpl_html_input_body, string $contentType = self::contentTypes['convertZplToHtml'][0])
    {
        list($response) = $this->convertZplToHtmlWithHttpInfo($zpl_html_input_body, $contentType);
        return $response;
    }

    /**
     * Operation convertZplToHtmlWithHttpInfo
     *
     * Decompile ZPL into editable HTML
     *
     * @param  \StripyHorse\Model\ZplHTMLInputBody $zpl_html_input_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['convertZplToHtml'] to see the possible values for this operation
     *
     * @throws \StripyHorse\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \StripyHorse\Model\ZplHTMLOutputBody|\StripyHorse\Model\ErrorModel, HTTP status code, HTTP response headers (array of strings)
     */
    public function convertZplToHtmlWithHttpInfo($zpl_html_input_body, string $contentType = self::contentTypes['convertZplToHtml'][0])
    {
        $request = $this->convertZplToHtmlRequest($zpl_html_input_body, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\StripyHorse\Model\ZplHTMLOutputBody',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\StripyHorse\Model\ErrorModel',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\StripyHorse\Model\ZplHTMLOutputBody',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\StripyHorse\Model\ZplHTMLOutputBody',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\StripyHorse\Model\ErrorModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation convertZplToHtmlAsync
     *
     * Decompile ZPL into editable HTML
     *
     * @param  \StripyHorse\Model\ZplHTMLInputBody $zpl_html_input_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['convertZplToHtml'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function convertZplToHtmlAsync($zpl_html_input_body, string $contentType = self::contentTypes['convertZplToHtml'][0])
    {
        return $this->convertZplToHtmlAsyncWithHttpInfo($zpl_html_input_body, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation convertZplToHtmlAsyncWithHttpInfo
     *
     * Decompile ZPL into editable HTML
     *
     * @param  \StripyHorse\Model\ZplHTMLInputBody $zpl_html_input_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['convertZplToHtml'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function convertZplToHtmlAsyncWithHttpInfo($zpl_html_input_body, string $contentType = self::contentTypes['convertZplToHtml'][0])
    {
        $returnType = '\StripyHorse\Model\ZplHTMLOutputBody';
        $request = $this->convertZplToHtmlRequest($zpl_html_input_body, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'convertZplToHtml'
     *
     * @param  \StripyHorse\Model\ZplHTMLInputBody $zpl_html_input_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['convertZplToHtml'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function convertZplToHtmlRequest($zpl_html_input_body, string $contentType = self::contentTypes['convertZplToHtml'][0])
    {

        // verify the required parameter 'zpl_html_input_body' is set
        if ($zpl_html_input_body === null || (is_array($zpl_html_input_body) && count($zpl_html_input_body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $zpl_html_input_body when calling convertZplToHtml'
            );
        }


        $resourcePath = '/v1/convert/zpl-html';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($zpl_html_input_body)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($zpl_html_input_body));
            } else {
                $httpBody = $zpl_html_input_body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Api-Key');
        if ($apiKey !== null) {
            $headers['X-Api-Key'] = $apiKey;
        }
        // this endpoint requires Bearer (sh_live_…) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation rasterizeUnicode
     *
     * Make Unicode ZPL printable on any Zebra
     *
     * @param  \StripyHorse\Model\UnicodeInputBody $unicode_input_body unicode_input_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['rasterizeUnicode'] to see the possible values for this operation
     *
     * @throws \StripyHorse\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \StripyHorse\Model\UnicodeOutputBody|\StripyHorse\Model\ErrorModel
     */
    public function rasterizeUnicode($unicode_input_body, string $contentType = self::contentTypes['rasterizeUnicode'][0])
    {
        list($response) = $this->rasterizeUnicodeWithHttpInfo($unicode_input_body, $contentType);
        return $response;
    }

    /**
     * Operation rasterizeUnicodeWithHttpInfo
     *
     * Make Unicode ZPL printable on any Zebra
     *
     * @param  \StripyHorse\Model\UnicodeInputBody $unicode_input_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['rasterizeUnicode'] to see the possible values for this operation
     *
     * @throws \StripyHorse\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \StripyHorse\Model\UnicodeOutputBody|\StripyHorse\Model\ErrorModel, HTTP status code, HTTP response headers (array of strings)
     */
    public function rasterizeUnicodeWithHttpInfo($unicode_input_body, string $contentType = self::contentTypes['rasterizeUnicode'][0])
    {
        $request = $this->rasterizeUnicodeRequest($unicode_input_body, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\StripyHorse\Model\UnicodeOutputBody',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\StripyHorse\Model\ErrorModel',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\StripyHorse\Model\UnicodeOutputBody',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\StripyHorse\Model\UnicodeOutputBody',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\StripyHorse\Model\ErrorModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation rasterizeUnicodeAsync
     *
     * Make Unicode ZPL printable on any Zebra
     *
     * @param  \StripyHorse\Model\UnicodeInputBody $unicode_input_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['rasterizeUnicode'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function rasterizeUnicodeAsync($unicode_input_body, string $contentType = self::contentTypes['rasterizeUnicode'][0])
    {
        return $this->rasterizeUnicodeAsyncWithHttpInfo($unicode_input_body, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation rasterizeUnicodeAsyncWithHttpInfo
     *
     * Make Unicode ZPL printable on any Zebra
     *
     * @param  \StripyHorse\Model\UnicodeInputBody $unicode_input_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['rasterizeUnicode'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function rasterizeUnicodeAsyncWithHttpInfo($unicode_input_body, string $contentType = self::contentTypes['rasterizeUnicode'][0])
    {
        $returnType = '\StripyHorse\Model\UnicodeOutputBody';
        $request = $this->rasterizeUnicodeRequest($unicode_input_body, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'rasterizeUnicode'
     *
     * @param  \StripyHorse\Model\UnicodeInputBody $unicode_input_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['rasterizeUnicode'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function rasterizeUnicodeRequest($unicode_input_body, string $contentType = self::contentTypes['rasterizeUnicode'][0])
    {

        // verify the required parameter 'unicode_input_body' is set
        if ($unicode_input_body === null || (is_array($unicode_input_body) && count($unicode_input_body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $unicode_input_body when calling rasterizeUnicode'
            );
        }


        $resourcePath = '/v1/unicode';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($unicode_input_body)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($unicode_input_body));
            } else {
                $httpBody = $unicode_input_body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Api-Key');
        if ($apiKey !== null) {
            $headers['X-Api-Key'] = $apiKey;
        }
        // this endpoint requires Bearer (sh_live_…) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation stampZpl
     *
     * Stamp an image onto ZPL labels
     *
     * @param  \StripyHorse\Model\StampInputBody $stamp_input_body stamp_input_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['stampZpl'] to see the possible values for this operation
     *
     * @throws \StripyHorse\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \StripyHorse\Model\StampOutputBody|\StripyHorse\Model\ErrorModel
     */
    public function stampZpl($stamp_input_body, string $contentType = self::contentTypes['stampZpl'][0])
    {
        list($response) = $this->stampZplWithHttpInfo($stamp_input_body, $contentType);
        return $response;
    }

    /**
     * Operation stampZplWithHttpInfo
     *
     * Stamp an image onto ZPL labels
     *
     * @param  \StripyHorse\Model\StampInputBody $stamp_input_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['stampZpl'] to see the possible values for this operation
     *
     * @throws \StripyHorse\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \StripyHorse\Model\StampOutputBody|\StripyHorse\Model\ErrorModel, HTTP status code, HTTP response headers (array of strings)
     */
    public function stampZplWithHttpInfo($stamp_input_body, string $contentType = self::contentTypes['stampZpl'][0])
    {
        $request = $this->stampZplRequest($stamp_input_body, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\StripyHorse\Model\StampOutputBody',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\StripyHorse\Model\ErrorModel',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\StripyHorse\Model\StampOutputBody',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\StripyHorse\Model\StampOutputBody',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\StripyHorse\Model\ErrorModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation stampZplAsync
     *
     * Stamp an image onto ZPL labels
     *
     * @param  \StripyHorse\Model\StampInputBody $stamp_input_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['stampZpl'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function stampZplAsync($stamp_input_body, string $contentType = self::contentTypes['stampZpl'][0])
    {
        return $this->stampZplAsyncWithHttpInfo($stamp_input_body, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation stampZplAsyncWithHttpInfo
     *
     * Stamp an image onto ZPL labels
     *
     * @param  \StripyHorse\Model\StampInputBody $stamp_input_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['stampZpl'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function stampZplAsyncWithHttpInfo($stamp_input_body, string $contentType = self::contentTypes['stampZpl'][0])
    {
        $returnType = '\StripyHorse\Model\StampOutputBody';
        $request = $this->stampZplRequest($stamp_input_body, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'stampZpl'
     *
     * @param  \StripyHorse\Model\StampInputBody $stamp_input_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['stampZpl'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function stampZplRequest($stamp_input_body, string $contentType = self::contentTypes['stampZpl'][0])
    {

        // verify the required parameter 'stamp_input_body' is set
        if ($stamp_input_body === null || (is_array($stamp_input_body) && count($stamp_input_body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $stamp_input_body when calling stampZpl'
            );
        }


        $resourcePath = '/v1/stamp';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($stamp_input_body)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($stamp_input_body));
            } else {
                $httpBody = $stamp_input_body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Api-Key');
        if ($apiKey !== null) {
            $headers['X-Api-Key'] = $apiKey;
        }
        // this endpoint requires Bearer (sh_live_…) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation voidZpl
     *
     * Stamp ZPL as void / do-not-ship
     *
     * @param  \StripyHorse\Model\VoidInputBody $void_input_body void_input_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['voidZpl'] to see the possible values for this operation
     *
     * @throws \StripyHorse\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \StripyHorse\Model\VoidOutputBody|\StripyHorse\Model\ErrorModel
     */
    public function voidZpl($void_input_body, string $contentType = self::contentTypes['voidZpl'][0])
    {
        list($response) = $this->voidZplWithHttpInfo($void_input_body, $contentType);
        return $response;
    }

    /**
     * Operation voidZplWithHttpInfo
     *
     * Stamp ZPL as void / do-not-ship
     *
     * @param  \StripyHorse\Model\VoidInputBody $void_input_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['voidZpl'] to see the possible values for this operation
     *
     * @throws \StripyHorse\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \StripyHorse\Model\VoidOutputBody|\StripyHorse\Model\ErrorModel, HTTP status code, HTTP response headers (array of strings)
     */
    public function voidZplWithHttpInfo($void_input_body, string $contentType = self::contentTypes['voidZpl'][0])
    {
        $request = $this->voidZplRequest($void_input_body, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\StripyHorse\Model\VoidOutputBody',
                        $request,
                        $response,
                    );
                default:
                    return $this->handleResponseWithDataType(
                        '\StripyHorse\Model\ErrorModel',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\StripyHorse\Model\VoidOutputBody',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\StripyHorse\Model\VoidOutputBody',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\StripyHorse\Model\ErrorModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation voidZplAsync
     *
     * Stamp ZPL as void / do-not-ship
     *
     * @param  \StripyHorse\Model\VoidInputBody $void_input_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['voidZpl'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function voidZplAsync($void_input_body, string $contentType = self::contentTypes['voidZpl'][0])
    {
        return $this->voidZplAsyncWithHttpInfo($void_input_body, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation voidZplAsyncWithHttpInfo
     *
     * Stamp ZPL as void / do-not-ship
     *
     * @param  \StripyHorse\Model\VoidInputBody $void_input_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['voidZpl'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function voidZplAsyncWithHttpInfo($void_input_body, string $contentType = self::contentTypes['voidZpl'][0])
    {
        $returnType = '\StripyHorse\Model\VoidOutputBody';
        $request = $this->voidZplRequest($void_input_body, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'voidZpl'
     *
     * @param  \StripyHorse\Model\VoidInputBody $void_input_body (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['voidZpl'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function voidZplRequest($void_input_body, string $contentType = self::contentTypes['voidZpl'][0])
    {

        // verify the required parameter 'void_input_body' is set
        if ($void_input_body === null || (is_array($void_input_body) && count($void_input_body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $void_input_body when calling voidZpl'
            );
        }


        $resourcePath = '/v1/void';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($void_input_body)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($void_input_body));
            } else {
                $httpBody = $void_input_body;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Api-Key');
        if ($apiKey !== null) {
            $headers['X-Api-Key'] = $apiKey;
        }
        // this endpoint requires Bearer (sh_live_…) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
