<?php
/**
 * Barcode
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  StripyHorse
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace StripyHorse\Model;

use \ArrayAccess;
use \StripyHorse\ObjectSerializer;

/**
 * Barcode Class Doc Comment
 *
 * @category Class
 * @package  StripyHorse
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Barcode implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'Barcode';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'blur_margin_dots' => 'int',
        'checks' => '\StripyHorse\Model\Check[]',
        'cross_dpi' => '\StripyHorse\Model\DPIVerdict[]',
        'format' => 'string',
        'module_dots' => 'float',
        'quiet_left_modules' => 'float',
        'quiet_right_modules' => 'float',
        'value' => 'string',
        'x_dimension_mm' => 'float'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'blur_margin_dots' => 'int64',
        'checks' => null,
        'cross_dpi' => null,
        'format' => null,
        'module_dots' => 'double',
        'quiet_left_modules' => 'double',
        'quiet_right_modules' => 'double',
        'value' => null,
        'x_dimension_mm' => 'double'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'blur_margin_dots' => false,
        'checks' => true,
        'cross_dpi' => true,
        'format' => false,
        'module_dots' => false,
        'quiet_left_modules' => false,
        'quiet_right_modules' => false,
        'value' => false,
        'x_dimension_mm' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'blur_margin_dots' => 'blurMarginDots',
        'checks' => 'checks',
        'cross_dpi' => 'crossDpi',
        'format' => 'format',
        'module_dots' => 'moduleDots',
        'quiet_left_modules' => 'quietLeftModules',
        'quiet_right_modules' => 'quietRightModules',
        'value' => 'value',
        'x_dimension_mm' => 'xDimensionMm'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'blur_margin_dots' => 'setBlurMarginDots',
        'checks' => 'setChecks',
        'cross_dpi' => 'setCrossDpi',
        'format' => 'setFormat',
        'module_dots' => 'setModuleDots',
        'quiet_left_modules' => 'setQuietLeftModules',
        'quiet_right_modules' => 'setQuietRightModules',
        'value' => 'setValue',
        'x_dimension_mm' => 'setXDimensionMm'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'blur_margin_dots' => 'getBlurMarginDots',
        'checks' => 'getChecks',
        'cross_dpi' => 'getCrossDpi',
        'format' => 'getFormat',
        'module_dots' => 'getModuleDots',
        'quiet_left_modules' => 'getQuietLeftModules',
        'quiet_right_modules' => 'getQuietRightModules',
        'value' => 'getValue',
        'x_dimension_mm' => 'getXDimensionMm'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('blur_margin_dots', $data ?? [], null);
        $this->setIfExists('checks', $data ?? [], null);
        $this->setIfExists('cross_dpi', $data ?? [], null);
        $this->setIfExists('format', $data ?? [], null);
        $this->setIfExists('module_dots', $data ?? [], null);
        $this->setIfExists('quiet_left_modules', $data ?? [], null);
        $this->setIfExists('quiet_right_modules', $data ?? [], null);
        $this->setIfExists('value', $data ?? [], null);
        $this->setIfExists('x_dimension_mm', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['blur_margin_dots'] === null) {
            $invalidProperties[] = "'blur_margin_dots' can't be null";
        }
        if ($this->container['checks'] === null && !$this->isNullableSetToNull('checks')) {
            $invalidProperties[] = "'checks' is required";
        }
        if ($this->container['format'] === null) {
            $invalidProperties[] = "'format' can't be null";
        }
        if ($this->container['value'] === null) {
            $invalidProperties[] = "'value' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets blur_margin_dots
     *
     * @return int
     */
    public function getBlurMarginDots()
    {
        return $this->container['blur_margin_dots'];
    }

    /**
     * Sets blur_margin_dots
     *
     * @param int $blur_margin_dots Largest blur radius the symbol survives; 0 = no margin
     *
     * @return self
     */
    public function setBlurMarginDots($blur_margin_dots)
    {
        if (is_null($blur_margin_dots)) {
            throw new \InvalidArgumentException('non-nullable blur_margin_dots cannot be null');
        }
        $this->container['blur_margin_dots'] = $blur_margin_dots;

        return $this;
    }

    /**
     * Gets checks
     *
     * @return \StripyHorse\Model\Check[]|null
     */
    public function getChecks()
    {
        return $this->container['checks'];
    }

    /**
     * Sets checks
     *
     * @param \StripyHorse\Model\Check[]|null $checks checks
     *
     * @return self
     */
    public function setChecks($checks)
    {
        if (is_null($checks)) {
            array_push($this->openAPINullablesSetToNull, 'checks');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('checks', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['checks'] = $checks;

        return $this;
    }

    /**
     * Gets cross_dpi
     *
     * @return \StripyHorse\Model\DPIVerdict[]|null
     */
    public function getCrossDpi()
    {
        return $this->container['cross_dpi'];
    }

    /**
     * Sets cross_dpi
     *
     * @param \StripyHorse\Model\DPIVerdict[]|null $cross_dpi X-dimension at other print densities, same dot counts
     *
     * @return self
     */
    public function setCrossDpi($cross_dpi)
    {
        if (is_null($cross_dpi)) {
            array_push($this->openAPINullablesSetToNull, 'cross_dpi');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cross_dpi', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cross_dpi'] = $cross_dpi;

        return $this;
    }

    /**
     * Gets format
     *
     * @return string
     */
    public function getFormat()
    {
        return $this->container['format'];
    }

    /**
     * Sets format
     *
     * @param string $format CODE_128, CODE_39, ITF, QR_CODE, DATA_MATRIX
     *
     * @return self
     */
    public function setFormat($format)
    {
        if (is_null($format)) {
            throw new \InvalidArgumentException('non-nullable format cannot be null');
        }
        $this->container['format'] = $format;

        return $this;
    }

    /**
     * Gets module_dots
     *
     * @return float|null
     */
    public function getModuleDots()
    {
        return $this->container['module_dots'];
    }

    /**
     * Sets module_dots
     *
     * @param float|null $module_dots Measured narrow-element width in printer dots (1D only)
     *
     * @return self
     */
    public function setModuleDots($module_dots)
    {
        if (is_null($module_dots)) {
            throw new \InvalidArgumentException('non-nullable module_dots cannot be null');
        }
        $this->container['module_dots'] = $module_dots;

        return $this;
    }

    /**
     * Gets quiet_left_modules
     *
     * @return float|null
     */
    public function getQuietLeftModules()
    {
        return $this->container['quiet_left_modules'];
    }

    /**
     * Sets quiet_left_modules
     *
     * @param float|null $quiet_left_modules quiet_left_modules
     *
     * @return self
     */
    public function setQuietLeftModules($quiet_left_modules)
    {
        if (is_null($quiet_left_modules)) {
            throw new \InvalidArgumentException('non-nullable quiet_left_modules cannot be null');
        }
        $this->container['quiet_left_modules'] = $quiet_left_modules;

        return $this;
    }

    /**
     * Gets quiet_right_modules
     *
     * @return float|null
     */
    public function getQuietRightModules()
    {
        return $this->container['quiet_right_modules'];
    }

    /**
     * Sets quiet_right_modules
     *
     * @param float|null $quiet_right_modules quiet_right_modules
     *
     * @return self
     */
    public function setQuietRightModules($quiet_right_modules)
    {
        if (is_null($quiet_right_modules)) {
            throw new \InvalidArgumentException('non-nullable quiet_right_modules cannot be null');
        }
        $this->container['quiet_right_modules'] = $quiet_right_modules;

        return $this;
    }

    /**
     * Gets value
     *
     * @return string
     */
    public function getValue()
    {
        return $this->container['value'];
    }

    /**
     * Sets value
     *
     * @param string $value value
     *
     * @return self
     */
    public function setValue($value)
    {
        if (is_null($value)) {
            throw new \InvalidArgumentException('non-nullable value cannot be null');
        }
        $this->container['value'] = $value;

        return $this;
    }

    /**
     * Gets x_dimension_mm
     *
     * @return float|null
     */
    public function getXDimensionMm()
    {
        return $this->container['x_dimension_mm'];
    }

    /**
     * Sets x_dimension_mm
     *
     * @param float|null $x_dimension_mm Physical narrow-element width at the analyzed density
     *
     * @return self
     */
    public function setXDimensionMm($x_dimension_mm)
    {
        if (is_null($x_dimension_mm)) {
            throw new \InvalidArgumentException('non-nullable x_dimension_mm cannot be null');
        }
        $this->container['x_dimension_mm'] = $x_dimension_mm;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


