<?php
/**
 * CreatePrinterInputBody
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  StripyHorse
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace StripyHorse\Model;

use \ArrayAccess;
use \StripyHorse\ObjectSerializer;

/**
 * CreatePrinterInputBody Class Doc Comment
 *
 * @category Class
 * @package  StripyHorse
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CreatePrinterInputBody implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'CreatePrinterInputBody';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'access_mode' => 'string',
        'anonymize' => 'bool',
        'dpmm' => 'int',
        'height_mm' => 'float',
        'mode' => 'string',
        'name' => 'string',
        'preset' => 'string',
        'shared_port' => 'bool',
        'webhook_url' => 'string',
        'width_mm' => 'float'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'access_mode' => null,
        'anonymize' => null,
        'dpmm' => 'int64',
        'height_mm' => 'double',
        'mode' => null,
        'name' => null,
        'preset' => null,
        'shared_port' => null,
        'webhook_url' => null,
        'width_mm' => 'double'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'access_mode' => false,
        'anonymize' => false,
        'dpmm' => false,
        'height_mm' => false,
        'mode' => false,
        'name' => false,
        'preset' => false,
        'shared_port' => false,
        'webhook_url' => false,
        'width_mm' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'access_mode' => 'accessMode',
        'anonymize' => 'anonymize',
        'dpmm' => 'dpmm',
        'height_mm' => 'heightMm',
        'mode' => 'mode',
        'name' => 'name',
        'preset' => 'preset',
        'shared_port' => 'sharedPort',
        'webhook_url' => 'webhookUrl',
        'width_mm' => 'widthMm'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'access_mode' => 'setAccessMode',
        'anonymize' => 'setAnonymize',
        'dpmm' => 'setDpmm',
        'height_mm' => 'setHeightMm',
        'mode' => 'setMode',
        'name' => 'setName',
        'preset' => 'setPreset',
        'shared_port' => 'setSharedPort',
        'webhook_url' => 'setWebhookUrl',
        'width_mm' => 'setWidthMm'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'access_mode' => 'getAccessMode',
        'anonymize' => 'getAnonymize',
        'dpmm' => 'getDpmm',
        'height_mm' => 'getHeightMm',
        'mode' => 'getMode',
        'name' => 'getName',
        'preset' => 'getPreset',
        'shared_port' => 'getSharedPort',
        'webhook_url' => 'getWebhookUrl',
        'width_mm' => 'getWidthMm'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const ACCESS_MODE_EMPTY = '';
    public const ACCESS_MODE_OPEN = 'open';
    public const ACCESS_MODE_TOKEN = 'token';
    public const ACCESS_MODE_IP = 'ip';
    public const DPMM_NUMBER_6 = 6;
    public const DPMM_NUMBER_8 = 8;
    public const DPMM_NUMBER_12 = 12;
    public const DPMM_NUMBER_24 = 24;
    public const MODE_EMPTY = '';
    public const MODE_EPHEMERAL = 'ephemeral';
    public const MODE_PERSISTENT = 'persistent';
    public const PRESET__4X6 = '4x6';
    public const PRESET__6X4 = '6x4';
    public const PRESET__4X8 = '4x8';
    public const PRESET__4X4 = '4x4';
    public const PRESET__4X3 = '4x3';
    public const PRESET__3X5 = '3x5';
    public const PRESET__5X3 = '5x3';
    public const PRESET__4X2 = '4x2';
    public const PRESET__2X4 = '2x4';
    public const PRESET__2X3 = '2x3';
    public const PRESET__3X2 = '3x2';
    public const PRESET__2X1 = '2x1';
    public const PRESET__3X1 = '3x1';
    public const PRESET__4X1 = '4x1';
    public const PRESET__2_25X1_25 = '2.25x1.25';
    public const PRESET__1_5X1 = '1.5x1';
    public const PRESET__1X1 = '1x1';
    public const PRESET_NETSTAMP = 'netstamp';
    public const PRESET_A6 = 'a6';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAccessModeAllowableValues()
    {
        return [
            self::ACCESS_MODE_EMPTY,
            self::ACCESS_MODE_OPEN,
            self::ACCESS_MODE_TOKEN,
            self::ACCESS_MODE_IP,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDpmmAllowableValues()
    {
        return [
            self::DPMM_NUMBER_6,
            self::DPMM_NUMBER_8,
            self::DPMM_NUMBER_12,
            self::DPMM_NUMBER_24,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getModeAllowableValues()
    {
        return [
            self::MODE_EMPTY,
            self::MODE_EPHEMERAL,
            self::MODE_PERSISTENT,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPresetAllowableValues()
    {
        return [
            self::PRESET__4X6,
            self::PRESET__6X4,
            self::PRESET__4X8,
            self::PRESET__4X4,
            self::PRESET__4X3,
            self::PRESET__3X5,
            self::PRESET__5X3,
            self::PRESET__4X2,
            self::PRESET__2X4,
            self::PRESET__2X3,
            self::PRESET__3X2,
            self::PRESET__2X1,
            self::PRESET__3X1,
            self::PRESET__4X1,
            self::PRESET__2_25X1_25,
            self::PRESET__1_5X1,
            self::PRESET__1X1,
            self::PRESET_NETSTAMP,
            self::PRESET_A6,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('access_mode', $data ?? [], null);
        $this->setIfExists('anonymize', $data ?? [], null);
        $this->setIfExists('dpmm', $data ?? [], null);
        $this->setIfExists('height_mm', $data ?? [], null);
        $this->setIfExists('mode', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('preset', $data ?? [], null);
        $this->setIfExists('shared_port', $data ?? [], null);
        $this->setIfExists('webhook_url', $data ?? [], null);
        $this->setIfExists('width_mm', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getAccessModeAllowableValues();
        if (!is_null($this->container['access_mode']) && !in_array($this->container['access_mode'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'access_mode', must be one of '%s'",
                $this->container['access_mode'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getDpmmAllowableValues();
        if (!is_null($this->container['dpmm']) && !in_array($this->container['dpmm'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'dpmm', must be one of '%s'",
                $this->container['dpmm'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['height_mm']) && ($this->container['height_mm'] < 0)) {
            $invalidProperties[] = "invalid value for 'height_mm', must be bigger than or equal to 0.";
        }

        $allowedValues = $this->getModeAllowableValues();
        if (!is_null($this->container['mode']) && !in_array($this->container['mode'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'mode', must be one of '%s'",
                $this->container['mode'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((mb_strlen($this->container['name']) < 1)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be bigger than or equal to 1.";
        }

        $allowedValues = $this->getPresetAllowableValues();
        if (!is_null($this->container['preset']) && !in_array($this->container['preset'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'preset', must be one of '%s'",
                $this->container['preset'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['width_mm']) && ($this->container['width_mm'] < 0)) {
            $invalidProperties[] = "invalid value for 'width_mm', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets access_mode
     *
     * @return string|null
     */
    public function getAccessMode()
    {
        return $this->container['access_mode'];
    }

    /**
     * Sets access_mode
     *
     * @param string|null $access_mode Who may print to the TCP port; default open. Use token from CI, where the source address is different every run.
     *
     * @return self
     */
    public function setAccessMode($access_mode)
    {
        if (is_null($access_mode)) {
            throw new \InvalidArgumentException('non-nullable access_mode cannot be null');
        }
        $allowedValues = $this->getAccessModeAllowableValues();
        if (!in_array($access_mode, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'access_mode', must be one of '%s'",
                    $access_mode,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['access_mode'] = $access_mode;

        return $this;
    }

    /**
     * Gets anonymize
     *
     * @return bool|null
     */
    public function getAnonymize()
    {
        return $this->container['anonymize'];
    }

    /**
     * Sets anonymize
     *
     * @param bool|null $anonymize Mask PII and strip graphics from every captured frame
     *
     * @return self
     */
    public function setAnonymize($anonymize)
    {
        if (is_null($anonymize)) {
            throw new \InvalidArgumentException('non-nullable anonymize cannot be null');
        }
        $this->container['anonymize'] = $anonymize;

        return $this;
    }

    /**
     * Gets dpmm
     *
     * @return int|null
     */
    public function getDpmm()
    {
        return $this->container['dpmm'];
    }

    /**
     * Sets dpmm
     *
     * @param int|null $dpmm Print density in dots/mm (152/203/300/600 dpi); default 8
     *
     * @return self
     */
    public function setDpmm($dpmm)
    {
        if (is_null($dpmm)) {
            throw new \InvalidArgumentException('non-nullable dpmm cannot be null');
        }
        $allowedValues = $this->getDpmmAllowableValues();
        if (!in_array($dpmm, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'dpmm', must be one of '%s'",
                    $dpmm,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['dpmm'] = $dpmm;

        return $this;
    }

    /**
     * Gets height_mm
     *
     * @return float|null
     */
    public function getHeightMm()
    {
        return $this->container['height_mm'];
    }

    /**
     * Sets height_mm
     *
     * @param float|null $height_mm height_mm
     *
     * @return self
     */
    public function setHeightMm($height_mm)
    {
        if (is_null($height_mm)) {
            throw new \InvalidArgumentException('non-nullable height_mm cannot be null');
        }
        if (($height_mm < 0)) {
            throw new \InvalidArgumentException('invalid value for $height_mm when calling CreatePrinterInputBody., must be bigger than or equal to 0.');
        }

        $this->container['height_mm'] = $height_mm;

        return $this;
    }

    /**
     * Gets mode
     *
     * @return string|null
     */
    public function getMode()
    {
        return $this->container['mode'];
    }

    /**
     * Sets mode
     *
     * @param string|null $mode mode
     *
     * @return self
     */
    public function setMode($mode)
    {
        if (is_null($mode)) {
            throw new \InvalidArgumentException('non-nullable mode cannot be null');
        }
        $allowedValues = $this->getModeAllowableValues();
        if (!in_array($mode, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'mode', must be one of '%s'",
                    $mode,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['mode'] = $mode;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }

        if ((mb_strlen($name) < 1)) {
            throw new \InvalidArgumentException('invalid length for $name when calling CreatePrinterInputBody., must be bigger than or equal to 1.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets preset
     *
     * @return string|null
     */
    public function getPreset()
    {
        return $this->container['preset'];
    }

    /**
     * Sets preset
     *
     * @param string|null $preset Named label size in inches; alternative to widthMm/heightMm
     *
     * @return self
     */
    public function setPreset($preset)
    {
        if (is_null($preset)) {
            throw new \InvalidArgumentException('non-nullable preset cannot be null');
        }
        $allowedValues = $this->getPresetAllowableValues();
        if (!in_array($preset, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'preset', must be one of '%s'",
                    $preset,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['preset'] = $preset;

        return $this;
    }

    /**
     * Gets shared_port
     *
     * @return bool|null
     */
    public function getSharedPort()
    {
        return $this->container['shared_port'];
    }

    /**
     * Sets shared_port
     *
     * @param bool|null $shared_port Put this printer on the shared router port instead of spending one of the plan's dedicated ports. It is then reached by naming it in the stream, a ZPL comment carrying the ingest token, which suits CI.
     *
     * @return self
     */
    public function setSharedPort($shared_port)
    {
        if (is_null($shared_port)) {
            throw new \InvalidArgumentException('non-nullable shared_port cannot be null');
        }
        $this->container['shared_port'] = $shared_port;

        return $this;
    }

    /**
     * Gets webhook_url
     *
     * @return string|null
     */
    public function getWebhookUrl()
    {
        return $this->container['webhook_url'];
    }

    /**
     * Sets webhook_url
     *
     * @param string|null $webhook_url webhook_url
     *
     * @return self
     */
    public function setWebhookUrl($webhook_url)
    {
        if (is_null($webhook_url)) {
            throw new \InvalidArgumentException('non-nullable webhook_url cannot be null');
        }
        $this->container['webhook_url'] = $webhook_url;

        return $this;
    }

    /**
     * Gets width_mm
     *
     * @return float|null
     */
    public function getWidthMm()
    {
        return $this->container['width_mm'];
    }

    /**
     * Sets width_mm
     *
     * @param float|null $width_mm width_mm
     *
     * @return self
     */
    public function setWidthMm($width_mm)
    {
        if (is_null($width_mm)) {
            throw new \InvalidArgumentException('non-nullable width_mm cannot be null');
        }
        if (($width_mm < 0)) {
            throw new \InvalidArgumentException('invalid value for $width_mm when calling CreatePrinterInputBody., must be bigger than or equal to 0.');
        }

        $this->container['width_mm'] = $width_mm;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


