<?php
/**
 * Element
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  StripyHorse
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace StripyHorse\Model;

use \ArrayAccess;
use \StripyHorse\ObjectSerializer;

/**
 * Element Class Doc Comment
 *
 * @category Class
 * @package  StripyHorse
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Element implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'Element';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'align' => 'string',
        'anchor' => 'string',
        'columns' => 'int',
        'corner_radius' => 'int',
        'data' => 'string',
        'diameter' => 'int',
        'error_correction' => 'string',
        'font' => 'string',
        'font_height' => 'int',
        'font_width' => 'int',
        'height' => 'int',
        'length' => 'int',
        'line_spacing' => 'int',
        'lines' => 'int',
        'magnification' => 'int',
        'max_width' => 'int',
        'mode' => 'string',
        'module_size' => 'int',
        'module_width' => 'int',
        'orientation' => 'string',
        'png' => 'string',
        'print_text' => 'bool',
        'rotation' => 'int',
        'rows' => 'int',
        'text' => 'string',
        'thickness' => 'int',
        'threshold' => 'int',
        'type' => 'string',
        'width' => 'int',
        'x' => 'int',
        'y' => 'int',
        'zpl' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'align' => null,
        'anchor' => null,
        'columns' => 'int64',
        'corner_radius' => 'int64',
        'data' => null,
        'diameter' => 'int64',
        'error_correction' => null,
        'font' => null,
        'font_height' => 'int64',
        'font_width' => 'int64',
        'height' => 'int64',
        'length' => 'int64',
        'line_spacing' => 'int64',
        'lines' => 'int64',
        'magnification' => 'int64',
        'max_width' => 'int64',
        'mode' => null,
        'module_size' => 'int64',
        'module_width' => 'int64',
        'orientation' => null,
        'png' => null,
        'print_text' => null,
        'rotation' => 'int64',
        'rows' => 'int64',
        'text' => null,
        'thickness' => 'int64',
        'threshold' => 'int64',
        'type' => null,
        'width' => 'int64',
        'x' => 'int64',
        'y' => 'int64',
        'zpl' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'align' => false,
        'anchor' => false,
        'columns' => false,
        'corner_radius' => false,
        'data' => false,
        'diameter' => false,
        'error_correction' => false,
        'font' => false,
        'font_height' => false,
        'font_width' => false,
        'height' => false,
        'length' => false,
        'line_spacing' => false,
        'lines' => false,
        'magnification' => false,
        'max_width' => false,
        'mode' => false,
        'module_size' => false,
        'module_width' => false,
        'orientation' => false,
        'png' => false,
        'print_text' => false,
        'rotation' => false,
        'rows' => false,
        'text' => false,
        'thickness' => false,
        'threshold' => false,
        'type' => false,
        'width' => false,
        'x' => false,
        'y' => false,
        'zpl' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'align' => 'align',
        'anchor' => 'anchor',
        'columns' => 'columns',
        'corner_radius' => 'cornerRadius',
        'data' => 'data',
        'diameter' => 'diameter',
        'error_correction' => 'errorCorrection',
        'font' => 'font',
        'font_height' => 'fontHeight',
        'font_width' => 'fontWidth',
        'height' => 'height',
        'length' => 'length',
        'line_spacing' => 'lineSpacing',
        'lines' => 'lines',
        'magnification' => 'magnification',
        'max_width' => 'maxWidth',
        'mode' => 'mode',
        'module_size' => 'moduleSize',
        'module_width' => 'moduleWidth',
        'orientation' => 'orientation',
        'png' => 'png',
        'print_text' => 'printText',
        'rotation' => 'rotation',
        'rows' => 'rows',
        'text' => 'text',
        'thickness' => 'thickness',
        'threshold' => 'threshold',
        'type' => 'type',
        'width' => 'width',
        'x' => 'x',
        'y' => 'y',
        'zpl' => 'zpl'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'align' => 'setAlign',
        'anchor' => 'setAnchor',
        'columns' => 'setColumns',
        'corner_radius' => 'setCornerRadius',
        'data' => 'setData',
        'diameter' => 'setDiameter',
        'error_correction' => 'setErrorCorrection',
        'font' => 'setFont',
        'font_height' => 'setFontHeight',
        'font_width' => 'setFontWidth',
        'height' => 'setHeight',
        'length' => 'setLength',
        'line_spacing' => 'setLineSpacing',
        'lines' => 'setLines',
        'magnification' => 'setMagnification',
        'max_width' => 'setMaxWidth',
        'mode' => 'setMode',
        'module_size' => 'setModuleSize',
        'module_width' => 'setModuleWidth',
        'orientation' => 'setOrientation',
        'png' => 'setPng',
        'print_text' => 'setPrintText',
        'rotation' => 'setRotation',
        'rows' => 'setRows',
        'text' => 'setText',
        'thickness' => 'setThickness',
        'threshold' => 'setThreshold',
        'type' => 'setType',
        'width' => 'setWidth',
        'x' => 'setX',
        'y' => 'setY',
        'zpl' => 'setZpl'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'align' => 'getAlign',
        'anchor' => 'getAnchor',
        'columns' => 'getColumns',
        'corner_radius' => 'getCornerRadius',
        'data' => 'getData',
        'diameter' => 'getDiameter',
        'error_correction' => 'getErrorCorrection',
        'font' => 'getFont',
        'font_height' => 'getFontHeight',
        'font_width' => 'getFontWidth',
        'height' => 'getHeight',
        'length' => 'getLength',
        'line_spacing' => 'getLineSpacing',
        'lines' => 'getLines',
        'magnification' => 'getMagnification',
        'max_width' => 'getMaxWidth',
        'mode' => 'getMode',
        'module_size' => 'getModuleSize',
        'module_width' => 'getModuleWidth',
        'orientation' => 'getOrientation',
        'png' => 'getPng',
        'print_text' => 'getPrintText',
        'rotation' => 'getRotation',
        'rows' => 'getRows',
        'text' => 'getText',
        'thickness' => 'getThickness',
        'threshold' => 'getThreshold',
        'type' => 'getType',
        'width' => 'getWidth',
        'x' => 'getX',
        'y' => 'getY',
        'zpl' => 'getZpl'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const ALIGN_EMPTY = '';
    public const ALIGN_LEFT = 'left';
    public const ALIGN_CENTER = 'center';
    public const ALIGN_RIGHT = 'right';
    public const ALIGN_JUSTIFY = 'justify';
    public const ANCHOR_EMPTY = '';
    public const ANCHOR_TOP_LEFT = 'topLeft';
    public const ANCHOR_BOTTOM_LEFT = 'bottomLeft';
    public const ANCHOR_TOP_RIGHT = 'topRight';
    public const ANCHOR_BOTTOM_RIGHT = 'bottomRight';
    public const ERROR_CORRECTION_EMPTY = '';
    public const ERROR_CORRECTION_L = 'L';
    public const ERROR_CORRECTION_M = 'M';
    public const ERROR_CORRECTION_Q = 'Q';
    public const ERROR_CORRECTION_H = 'H';
    public const MODE_EMPTY = '';
    public const MODE_N = 'N';
    public const MODE_U = 'U';
    public const MODE_A = 'A';
    public const MODE_D = 'D';
    public const ORIENTATION_EMPTY = '';
    public const ORIENTATION_H = 'h';
    public const ORIENTATION_V = 'v';
    public const ROTATION_NUMBER_0 = 0;
    public const ROTATION_NUMBER_90 = 90;
    public const ROTATION_NUMBER_180 = 180;
    public const ROTATION_NUMBER_270 = 270;
    public const TYPE_TEXT = 'text';
    public const TYPE_BARCODE128 = 'barcode128';
    public const TYPE_BARCODE39 = 'barcode39';
    public const TYPE_QR = 'qr';
    public const TYPE_DATAMATRIX = 'datamatrix';
    public const TYPE_BOX = 'box';
    public const TYPE_LINE = 'line';
    public const TYPE_CIRCLE = 'circle';
    public const TYPE_GRID = 'grid';
    public const TYPE_IMAGE = 'image';
    public const TYPE_RAW = 'raw';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAlignAllowableValues()
    {
        return [
            self::ALIGN_EMPTY,
            self::ALIGN_LEFT,
            self::ALIGN_CENTER,
            self::ALIGN_RIGHT,
            self::ALIGN_JUSTIFY,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAnchorAllowableValues()
    {
        return [
            self::ANCHOR_EMPTY,
            self::ANCHOR_TOP_LEFT,
            self::ANCHOR_BOTTOM_LEFT,
            self::ANCHOR_TOP_RIGHT,
            self::ANCHOR_BOTTOM_RIGHT,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getErrorCorrectionAllowableValues()
    {
        return [
            self::ERROR_CORRECTION_EMPTY,
            self::ERROR_CORRECTION_L,
            self::ERROR_CORRECTION_M,
            self::ERROR_CORRECTION_Q,
            self::ERROR_CORRECTION_H,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getModeAllowableValues()
    {
        return [
            self::MODE_EMPTY,
            self::MODE_N,
            self::MODE_U,
            self::MODE_A,
            self::MODE_D,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getOrientationAllowableValues()
    {
        return [
            self::ORIENTATION_EMPTY,
            self::ORIENTATION_H,
            self::ORIENTATION_V,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getRotationAllowableValues()
    {
        return [
            self::ROTATION_NUMBER_0,
            self::ROTATION_NUMBER_90,
            self::ROTATION_NUMBER_180,
            self::ROTATION_NUMBER_270,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_TEXT,
            self::TYPE_BARCODE128,
            self::TYPE_BARCODE39,
            self::TYPE_QR,
            self::TYPE_DATAMATRIX,
            self::TYPE_BOX,
            self::TYPE_LINE,
            self::TYPE_CIRCLE,
            self::TYPE_GRID,
            self::TYPE_IMAGE,
            self::TYPE_RAW,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('align', $data ?? [], null);
        $this->setIfExists('anchor', $data ?? [], null);
        $this->setIfExists('columns', $data ?? [], null);
        $this->setIfExists('corner_radius', $data ?? [], null);
        $this->setIfExists('data', $data ?? [], null);
        $this->setIfExists('diameter', $data ?? [], null);
        $this->setIfExists('error_correction', $data ?? [], null);
        $this->setIfExists('font', $data ?? [], null);
        $this->setIfExists('font_height', $data ?? [], null);
        $this->setIfExists('font_width', $data ?? [], null);
        $this->setIfExists('height', $data ?? [], null);
        $this->setIfExists('length', $data ?? [], null);
        $this->setIfExists('line_spacing', $data ?? [], null);
        $this->setIfExists('lines', $data ?? [], null);
        $this->setIfExists('magnification', $data ?? [], null);
        $this->setIfExists('max_width', $data ?? [], null);
        $this->setIfExists('mode', $data ?? [], null);
        $this->setIfExists('module_size', $data ?? [], null);
        $this->setIfExists('module_width', $data ?? [], null);
        $this->setIfExists('orientation', $data ?? [], null);
        $this->setIfExists('png', $data ?? [], null);
        $this->setIfExists('print_text', $data ?? [], null);
        $this->setIfExists('rotation', $data ?? [], null);
        $this->setIfExists('rows', $data ?? [], null);
        $this->setIfExists('text', $data ?? [], null);
        $this->setIfExists('thickness', $data ?? [], null);
        $this->setIfExists('threshold', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('width', $data ?? [], null);
        $this->setIfExists('x', $data ?? [], null);
        $this->setIfExists('y', $data ?? [], null);
        $this->setIfExists('zpl', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getAlignAllowableValues();
        if (!is_null($this->container['align']) && !in_array($this->container['align'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'align', must be one of '%s'",
                $this->container['align'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getAnchorAllowableValues();
        if (!is_null($this->container['anchor']) && !in_array($this->container['anchor'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'anchor', must be one of '%s'",
                $this->container['anchor'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['columns']) && ($this->container['columns'] > 50)) {
            $invalidProperties[] = "invalid value for 'columns', must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['columns']) && ($this->container['columns'] < 0)) {
            $invalidProperties[] = "invalid value for 'columns', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['corner_radius']) && ($this->container['corner_radius'] > 8)) {
            $invalidProperties[] = "invalid value for 'corner_radius', must be smaller than or equal to 8.";
        }

        if (!is_null($this->container['corner_radius']) && ($this->container['corner_radius'] < 0)) {
            $invalidProperties[] = "invalid value for 'corner_radius', must be bigger than or equal to 0.";
        }

        $allowedValues = $this->getErrorCorrectionAllowableValues();
        if (!is_null($this->container['error_correction']) && !in_array($this->container['error_correction'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'error_correction', must be one of '%s'",
                $this->container['error_correction'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['font_height']) && ($this->container['font_height'] > 10000)) {
            $invalidProperties[] = "invalid value for 'font_height', must be smaller than or equal to 10000.";
        }

        $allowedValues = $this->getModeAllowableValues();
        if (!is_null($this->container['mode']) && !in_array($this->container['mode'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'mode', must be one of '%s'",
                $this->container['mode'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getOrientationAllowableValues();
        if (!is_null($this->container['orientation']) && !in_array($this->container['orientation'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'orientation', must be one of '%s'",
                $this->container['orientation'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getRotationAllowableValues();
        if (!is_null($this->container['rotation']) && !in_array($this->container['rotation'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'rotation', must be one of '%s'",
                $this->container['rotation'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['rows']) && ($this->container['rows'] > 50)) {
            $invalidProperties[] = "invalid value for 'rows', must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['rows']) && ($this->container['rows'] < 0)) {
            $invalidProperties[] = "invalid value for 'rows', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['threshold']) && ($this->container['threshold'] > 255)) {
            $invalidProperties[] = "invalid value for 'threshold', must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['threshold']) && ($this->container['threshold'] < 0)) {
            $invalidProperties[] = "invalid value for 'threshold', must be bigger than or equal to 0.";
        }

        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($this->container['type']) && !in_array($this->container['type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'type', must be one of '%s'",
                $this->container['type'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['x']) && ($this->container['x'] < 0)) {
            $invalidProperties[] = "invalid value for 'x', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['y']) && ($this->container['y'] < 0)) {
            $invalidProperties[] = "invalid value for 'y', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets align
     *
     * @return string|null
     */
    public function getAlign()
    {
        return $this->container['align'];
    }

    /**
     * Sets align
     *
     * @param string|null $align Alignment when wrapping
     *
     * @return self
     */
    public function setAlign($align)
    {
        if (is_null($align)) {
            throw new \InvalidArgumentException('non-nullable align cannot be null');
        }
        $allowedValues = $this->getAlignAllowableValues();
        if (!in_array($align, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'align', must be one of '%s'",
                    $align,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['align'] = $align;

        return $this;
    }

    /**
     * Gets anchor
     *
     * @return string|null
     */
    public function getAnchor()
    {
        return $this->container['anchor'];
    }

    /**
     * Sets anchor
     *
     * @param string|null $anchor Which corner x,y names. topLeft (^FO, default); bottomLeft (^FT: the text baseline, what most designer-exported ZPL uses); the Right variants make x the field's right edge (ZPL justification 1)
     *
     * @return self
     */
    public function setAnchor($anchor)
    {
        if (is_null($anchor)) {
            throw new \InvalidArgumentException('non-nullable anchor cannot be null');
        }
        $allowedValues = $this->getAnchorAllowableValues();
        if (!in_array($anchor, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'anchor', must be one of '%s'",
                    $anchor,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['anchor'] = $anchor;

        return $this;
    }

    /**
     * Gets columns
     *
     * @return int|null
     */
    public function getColumns()
    {
        return $this->container['columns'];
    }

    /**
     * Sets columns
     *
     * @param int|null $columns Grid columns (default 1)
     *
     * @return self
     */
    public function setColumns($columns)
    {
        if (is_null($columns)) {
            throw new \InvalidArgumentException('non-nullable columns cannot be null');
        }
        if (($columns > 50)) {
            throw new \InvalidArgumentException('invalid value for $columns when calling Element., must be smaller than or equal to 50.');
        }
        if (($columns < 0)) {
            throw new \InvalidArgumentException('invalid value for $columns when calling Element., must be bigger than or equal to 0.');
        }

        $this->container['columns'] = $columns;

        return $this;
    }

    /**
     * Gets corner_radius
     *
     * @return int|null
     */
    public function getCornerRadius()
    {
        return $this->container['corner_radius'];
    }

    /**
     * Sets corner_radius
     *
     * @param int|null $corner_radius Box corner rounding 0-8
     *
     * @return self
     */
    public function setCornerRadius($corner_radius)
    {
        if (is_null($corner_radius)) {
            throw new \InvalidArgumentException('non-nullable corner_radius cannot be null');
        }
        if (($corner_radius > 8)) {
            throw new \InvalidArgumentException('invalid value for $corner_radius when calling Element., must be smaller than or equal to 8.');
        }
        if (($corner_radius < 0)) {
            throw new \InvalidArgumentException('invalid value for $corner_radius when calling Element., must be bigger than or equal to 0.');
        }

        $this->container['corner_radius'] = $corner_radius;

        return $this;
    }

    /**
     * Gets data
     *
     * @return string|null
     */
    public function getData()
    {
        return $this->container['data'];
    }

    /**
     * Sets data
     *
     * @param string|null $data Barcode payload; {{name}} interpolates
     *
     * @return self
     */
    public function setData($data)
    {
        if (is_null($data)) {
            throw new \InvalidArgumentException('non-nullable data cannot be null');
        }
        $this->container['data'] = $data;

        return $this;
    }

    /**
     * Gets diameter
     *
     * @return int|null
     */
    public function getDiameter()
    {
        return $this->container['diameter'];
    }

    /**
     * Sets diameter
     *
     * @param int|null $diameter Circle diameter in dots
     *
     * @return self
     */
    public function setDiameter($diameter)
    {
        if (is_null($diameter)) {
            throw new \InvalidArgumentException('non-nullable diameter cannot be null');
        }
        $this->container['diameter'] = $diameter;

        return $this;
    }

    /**
     * Gets error_correction
     *
     * @return string|null
     */
    public function getErrorCorrection()
    {
        return $this->container['error_correction'];
    }

    /**
     * Sets error_correction
     *
     * @param string|null $error_correction QR error correction (default M)
     *
     * @return self
     */
    public function setErrorCorrection($error_correction)
    {
        if (is_null($error_correction)) {
            throw new \InvalidArgumentException('non-nullable error_correction cannot be null');
        }
        $allowedValues = $this->getErrorCorrectionAllowableValues();
        if (!in_array($error_correction, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'error_correction', must be one of '%s'",
                    $error_correction,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['error_correction'] = $error_correction;

        return $this;
    }

    /**
     * Gets font
     *
     * @return string|null
     */
    public function getFont()
    {
        return $this->container['font'];
    }

    /**
     * Sets font
     *
     * @param string|null $font Printer font: 0 (scalable, default) or A-Z
     *
     * @return self
     */
    public function setFont($font)
    {
        if (is_null($font)) {
            throw new \InvalidArgumentException('non-nullable font cannot be null');
        }
        $this->container['font'] = $font;

        return $this;
    }

    /**
     * Gets font_height
     *
     * @return int|null
     */
    public function getFontHeight()
    {
        return $this->container['font_height'];
    }

    /**
     * Sets font_height
     *
     * @param int|null $font_height Character height in dots (text)
     *
     * @return self
     */
    public function setFontHeight($font_height)
    {
        if (is_null($font_height)) {
            throw new \InvalidArgumentException('non-nullable font_height cannot be null');
        }
        if (($font_height > 10000)) {
            throw new \InvalidArgumentException('invalid value for $font_height when calling Element., must be smaller than or equal to 10000.');
        }

        $this->container['font_height'] = $font_height;

        return $this;
    }

    /**
     * Gets font_width
     *
     * @return int|null
     */
    public function getFontWidth()
    {
        return $this->container['font_width'];
    }

    /**
     * Sets font_width
     *
     * @param int|null $font_width Character width in dots; 0 follows fontHeight
     *
     * @return self
     */
    public function setFontWidth($font_width)
    {
        if (is_null($font_width)) {
            throw new \InvalidArgumentException('non-nullable font_width cannot be null');
        }
        $this->container['font_width'] = $font_width;

        return $this;
    }

    /**
     * Gets height
     *
     * @return int|null
     */
    public function getHeight()
    {
        return $this->container['height'];
    }

    /**
     * Sets height
     *
     * @param int|null $height Bar height in dots (1D) / box height in dots (box)
     *
     * @return self
     */
    public function setHeight($height)
    {
        if (is_null($height)) {
            throw new \InvalidArgumentException('non-nullable height cannot be null');
        }
        $this->container['height'] = $height;

        return $this;
    }

    /**
     * Gets length
     *
     * @return int|null
     */
    public function getLength()
    {
        return $this->container['length'];
    }

    /**
     * Sets length
     *
     * @param int|null $length Line length in dots
     *
     * @return self
     */
    public function setLength($length)
    {
        if (is_null($length)) {
            throw new \InvalidArgumentException('non-nullable length cannot be null');
        }
        $this->container['length'] = $length;

        return $this;
    }

    /**
     * Gets line_spacing
     *
     * @return int|null
     */
    public function getLineSpacing()
    {
        return $this->container['line_spacing'];
    }

    /**
     * Sets line_spacing
     *
     * @param int|null $line_spacing Extra dots between wrapped lines
     *
     * @return self
     */
    public function setLineSpacing($line_spacing)
    {
        if (is_null($line_spacing)) {
            throw new \InvalidArgumentException('non-nullable line_spacing cannot be null');
        }
        $this->container['line_spacing'] = $line_spacing;

        return $this;
    }

    /**
     * Gets lines
     *
     * @return int|null
     */
    public function getLines()
    {
        return $this->container['lines'];
    }

    /**
     * Sets lines
     *
     * @param int|null $lines Max lines when wrapping (default 1)
     *
     * @return self
     */
    public function setLines($lines)
    {
        if (is_null($lines)) {
            throw new \InvalidArgumentException('non-nullable lines cannot be null');
        }
        $this->container['lines'] = $lines;

        return $this;
    }

    /**
     * Gets magnification
     *
     * @return int|null
     */
    public function getMagnification()
    {
        return $this->container['magnification'];
    }

    /**
     * Sets magnification
     *
     * @param int|null $magnification QR module magnification (default 3)
     *
     * @return self
     */
    public function setMagnification($magnification)
    {
        if (is_null($magnification)) {
            throw new \InvalidArgumentException('non-nullable magnification cannot be null');
        }
        $this->container['magnification'] = $magnification;

        return $this;
    }

    /**
     * Gets max_width
     *
     * @return int|null
     */
    public function getMaxWidth()
    {
        return $this->container['max_width'];
    }

    /**
     * Sets max_width
     *
     * @param int|null $max_width Wrap text into a block this many dots wide
     *
     * @return self
     */
    public function setMaxWidth($max_width)
    {
        if (is_null($max_width)) {
            throw new \InvalidArgumentException('non-nullable max_width cannot be null');
        }
        $this->container['max_width'] = $max_width;

        return $this;
    }

    /**
     * Gets mode
     *
     * @return string|null
     */
    public function getMode()
    {
        return $this->container['mode'];
    }

    /**
     * Sets mode
     *
     * @param string|null $mode Code 128 mode: N none (default), U UCC case, A automatic subset switching, D UCC/EAN application identifiers
     *
     * @return self
     */
    public function setMode($mode)
    {
        if (is_null($mode)) {
            throw new \InvalidArgumentException('non-nullable mode cannot be null');
        }
        $allowedValues = $this->getModeAllowableValues();
        if (!in_array($mode, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'mode', must be one of '%s'",
                    $mode,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['mode'] = $mode;

        return $this;
    }

    /**
     * Gets module_size
     *
     * @return int|null
     */
    public function getModuleSize()
    {
        return $this->container['module_size'];
    }

    /**
     * Sets module_size
     *
     * @param int|null $module_size DataMatrix module size in dots (default 4)
     *
     * @return self
     */
    public function setModuleSize($module_size)
    {
        if (is_null($module_size)) {
            throw new \InvalidArgumentException('non-nullable module_size cannot be null');
        }
        $this->container['module_size'] = $module_size;

        return $this;
    }

    /**
     * Gets module_width
     *
     * @return int|null
     */
    public function getModuleWidth()
    {
        return $this->container['module_width'];
    }

    /**
     * Sets module_width
     *
     * @param int|null $module_width Narrow element width in dots (1D; default 3)
     *
     * @return self
     */
    public function setModuleWidth($module_width)
    {
        if (is_null($module_width)) {
            throw new \InvalidArgumentException('non-nullable module_width cannot be null');
        }
        $this->container['module_width'] = $module_width;

        return $this;
    }

    /**
     * Gets orientation
     *
     * @return string|null
     */
    public function getOrientation()
    {
        return $this->container['orientation'];
    }

    /**
     * Sets orientation
     *
     * @param string|null $orientation Line direction
     *
     * @return self
     */
    public function setOrientation($orientation)
    {
        if (is_null($orientation)) {
            throw new \InvalidArgumentException('non-nullable orientation cannot be null');
        }
        $allowedValues = $this->getOrientationAllowableValues();
        if (!in_array($orientation, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'orientation', must be one of '%s'",
                    $orientation,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['orientation'] = $orientation;

        return $this;
    }

    /**
     * Gets png
     *
     * @return string|null
     */
    public function getPng()
    {
        return $this->container['png'];
    }

    /**
     * Sets png
     *
     * @param string|null $png PNG/GIF/JPEG, base64-encoded
     *
     * @return self
     */
    public function setPng($png)
    {
        if (is_null($png)) {
            throw new \InvalidArgumentException('non-nullable png cannot be null');
        }
        $this->container['png'] = $png;

        return $this;
    }

    /**
     * Gets print_text
     *
     * @return bool|null
     */
    public function getPrintText()
    {
        return $this->container['print_text'];
    }

    /**
     * Sets print_text
     *
     * @param bool|null $print_text Print the human-readable line under 1D barcodes (default true)
     *
     * @return self
     */
    public function setPrintText($print_text)
    {
        if (is_null($print_text)) {
            throw new \InvalidArgumentException('non-nullable print_text cannot be null');
        }
        $this->container['print_text'] = $print_text;

        return $this;
    }

    /**
     * Gets rotation
     *
     * @return int|null
     */
    public function getRotation()
    {
        return $this->container['rotation'];
    }

    /**
     * Sets rotation
     *
     * @param int|null $rotation rotation
     *
     * @return self
     */
    public function setRotation($rotation)
    {
        if (is_null($rotation)) {
            throw new \InvalidArgumentException('non-nullable rotation cannot be null');
        }
        $allowedValues = $this->getRotationAllowableValues();
        if (!in_array($rotation, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'rotation', must be one of '%s'",
                    $rotation,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['rotation'] = $rotation;

        return $this;
    }

    /**
     * Gets rows
     *
     * @return int|null
     */
    public function getRows()
    {
        return $this->container['rows'];
    }

    /**
     * Sets rows
     *
     * @param int|null $rows Grid rows (default 1)
     *
     * @return self
     */
    public function setRows($rows)
    {
        if (is_null($rows)) {
            throw new \InvalidArgumentException('non-nullable rows cannot be null');
        }
        if (($rows > 50)) {
            throw new \InvalidArgumentException('invalid value for $rows when calling Element., must be smaller than or equal to 50.');
        }
        if (($rows < 0)) {
            throw new \InvalidArgumentException('invalid value for $rows when calling Element., must be bigger than or equal to 0.');
        }

        $this->container['rows'] = $rows;

        return $this;
    }

    /**
     * Gets text
     *
     * @return string|null
     */
    public function getText()
    {
        return $this->container['text'];
    }

    /**
     * Sets text
     *
     * @param string|null $text Text content; {{name}} interpolates from variables
     *
     * @return self
     */
    public function setText($text)
    {
        if (is_null($text)) {
            throw new \InvalidArgumentException('non-nullable text cannot be null');
        }
        $this->container['text'] = $text;

        return $this;
    }

    /**
     * Gets thickness
     *
     * @return int|null
     */
    public function getThickness()
    {
        return $this->container['thickness'];
    }

    /**
     * Sets thickness
     *
     * @param int|null $thickness Stroke thickness in dots (default 1)
     *
     * @return self
     */
    public function setThickness($thickness)
    {
        if (is_null($thickness)) {
            throw new \InvalidArgumentException('non-nullable thickness cannot be null');
        }
        $this->container['thickness'] = $thickness;

        return $this;
    }

    /**
     * Gets threshold
     *
     * @return int|null
     */
    public function getThreshold()
    {
        return $this->container['threshold'];
    }

    /**
     * Sets threshold
     *
     * @param int|null $threshold Bitonal threshold (default 128)
     *
     * @return self
     */
    public function setThreshold($threshold)
    {
        if (is_null($threshold)) {
            throw new \InvalidArgumentException('non-nullable threshold cannot be null');
        }
        if (($threshold > 255)) {
            throw new \InvalidArgumentException('invalid value for $threshold when calling Element., must be smaller than or equal to 255.');
        }
        if (($threshold < 0)) {
            throw new \InvalidArgumentException('invalid value for $threshold when calling Element., must be bigger than or equal to 0.');
        }

        $this->container['threshold'] = $threshold;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type What to place
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!in_array($type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'type', must be one of '%s'",
                    $type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets width
     *
     * @return int|null
     */
    public function getWidth()
    {
        return $this->container['width'];
    }

    /**
     * Sets width
     *
     * @param int|null $width Box/image width in dots
     *
     * @return self
     */
    public function setWidth($width)
    {
        if (is_null($width)) {
            throw new \InvalidArgumentException('non-nullable width cannot be null');
        }
        $this->container['width'] = $width;

        return $this;
    }

    /**
     * Gets x
     *
     * @return int|null
     */
    public function getX()
    {
        return $this->container['x'];
    }

    /**
     * Sets x
     *
     * @param int|null $x Left edge in dots
     *
     * @return self
     */
    public function setX($x)
    {
        if (is_null($x)) {
            throw new \InvalidArgumentException('non-nullable x cannot be null');
        }
        if (($x < 0)) {
            throw new \InvalidArgumentException('invalid value for $x when calling Element., must be bigger than or equal to 0.');
        }

        $this->container['x'] = $x;

        return $this;
    }

    /**
     * Gets y
     *
     * @return int|null
     */
    public function getY()
    {
        return $this->container['y'];
    }

    /**
     * Sets y
     *
     * @param int|null $y Top edge in dots
     *
     * @return self
     */
    public function setY($y)
    {
        if (is_null($y)) {
            throw new \InvalidArgumentException('non-nullable y cannot be null');
        }
        if (($y < 0)) {
            throw new \InvalidArgumentException('invalid value for $y when calling Element., must be bigger than or equal to 0.');
        }

        $this->container['y'] = $y;

        return $this;
    }

    /**
     * Gets zpl
     *
     * @return string|null
     */
    public function getZpl()
    {
        return $this->container['zpl'];
    }

    /**
     * Sets zpl
     *
     * @param string|null $zpl Verbatim ZPL commands (raw only) - the escape hatch
     *
     * @return self
     */
    public function setZpl($zpl)
    {
        if (is_null($zpl)) {
            throw new \InvalidArgumentException('non-nullable zpl cannot be null');
        }
        $this->container['zpl'] = $zpl;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


