<?php
/**
 * HostStatus
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  StripyHorse
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ben@stripyhorse.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace StripyHorse\Model;

use \ArrayAccess;
use \StripyHorse\ObjectSerializer;

/**
 * HostStatus Class Doc Comment
 *
 * @category Class
 * @package  StripyHorse
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class HostStatus implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'HostStatus';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'blocking' => 'bool',
        'buffer_full' => 'bool',
        'comm_settings' => 'string',
        'corrupt_ram' => 'bool',
        'diagnostic_mode' => 'bool',
        'formats_in_buffer' => 'int',
        'function_settings' => 'string',
        'graphics_stored' => 'int',
        'head_up' => 'bool',
        'label_length_dots' => 'int',
        'labels_remaining' => 'int',
        'over_temp' => 'bool',
        'paper_out' => 'bool',
        'partial_format' => 'bool',
        'password' => 'string',
        'paused' => 'bool',
        'print_mode' => 'string',
        'ribbon_out' => 'bool',
        'static_ram' => 'bool',
        'thermal_transfer' => 'bool',
        'under_temp' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'blocking' => null,
        'buffer_full' => null,
        'comm_settings' => null,
        'corrupt_ram' => null,
        'diagnostic_mode' => null,
        'formats_in_buffer' => 'int64',
        'function_settings' => null,
        'graphics_stored' => 'int64',
        'head_up' => null,
        'label_length_dots' => 'int64',
        'labels_remaining' => 'int64',
        'over_temp' => null,
        'paper_out' => null,
        'partial_format' => null,
        'password' => null,
        'paused' => null,
        'print_mode' => null,
        'ribbon_out' => null,
        'static_ram' => null,
        'thermal_transfer' => null,
        'under_temp' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'blocking' => false,
        'buffer_full' => false,
        'comm_settings' => false,
        'corrupt_ram' => false,
        'diagnostic_mode' => false,
        'formats_in_buffer' => false,
        'function_settings' => false,
        'graphics_stored' => false,
        'head_up' => false,
        'label_length_dots' => false,
        'labels_remaining' => false,
        'over_temp' => false,
        'paper_out' => false,
        'partial_format' => false,
        'password' => false,
        'paused' => false,
        'print_mode' => false,
        'ribbon_out' => false,
        'static_ram' => false,
        'thermal_transfer' => false,
        'under_temp' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'blocking' => 'blocking',
        'buffer_full' => 'bufferFull',
        'comm_settings' => 'commSettings',
        'corrupt_ram' => 'corruptRam',
        'diagnostic_mode' => 'diagnosticMode',
        'formats_in_buffer' => 'formatsInBuffer',
        'function_settings' => 'functionSettings',
        'graphics_stored' => 'graphicsStored',
        'head_up' => 'headUp',
        'label_length_dots' => 'labelLengthDots',
        'labels_remaining' => 'labelsRemaining',
        'over_temp' => 'overTemp',
        'paper_out' => 'paperOut',
        'partial_format' => 'partialFormat',
        'password' => 'password',
        'paused' => 'paused',
        'print_mode' => 'printMode',
        'ribbon_out' => 'ribbonOut',
        'static_ram' => 'staticRam',
        'thermal_transfer' => 'thermalTransfer',
        'under_temp' => 'underTemp'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'blocking' => 'setBlocking',
        'buffer_full' => 'setBufferFull',
        'comm_settings' => 'setCommSettings',
        'corrupt_ram' => 'setCorruptRam',
        'diagnostic_mode' => 'setDiagnosticMode',
        'formats_in_buffer' => 'setFormatsInBuffer',
        'function_settings' => 'setFunctionSettings',
        'graphics_stored' => 'setGraphicsStored',
        'head_up' => 'setHeadUp',
        'label_length_dots' => 'setLabelLengthDots',
        'labels_remaining' => 'setLabelsRemaining',
        'over_temp' => 'setOverTemp',
        'paper_out' => 'setPaperOut',
        'partial_format' => 'setPartialFormat',
        'password' => 'setPassword',
        'paused' => 'setPaused',
        'print_mode' => 'setPrintMode',
        'ribbon_out' => 'setRibbonOut',
        'static_ram' => 'setStaticRam',
        'thermal_transfer' => 'setThermalTransfer',
        'under_temp' => 'setUnderTemp'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'blocking' => 'getBlocking',
        'buffer_full' => 'getBufferFull',
        'comm_settings' => 'getCommSettings',
        'corrupt_ram' => 'getCorruptRam',
        'diagnostic_mode' => 'getDiagnosticMode',
        'formats_in_buffer' => 'getFormatsInBuffer',
        'function_settings' => 'getFunctionSettings',
        'graphics_stored' => 'getGraphicsStored',
        'head_up' => 'getHeadUp',
        'label_length_dots' => 'getLabelLengthDots',
        'labels_remaining' => 'getLabelsRemaining',
        'over_temp' => 'getOverTemp',
        'paper_out' => 'getPaperOut',
        'partial_format' => 'getPartialFormat',
        'password' => 'getPassword',
        'paused' => 'getPaused',
        'print_mode' => 'getPrintMode',
        'ribbon_out' => 'getRibbonOut',
        'static_ram' => 'getStaticRam',
        'thermal_transfer' => 'getThermalTransfer',
        'under_temp' => 'getUnderTemp'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('blocking', $data ?? [], null);
        $this->setIfExists('buffer_full', $data ?? [], null);
        $this->setIfExists('comm_settings', $data ?? [], null);
        $this->setIfExists('corrupt_ram', $data ?? [], null);
        $this->setIfExists('diagnostic_mode', $data ?? [], null);
        $this->setIfExists('formats_in_buffer', $data ?? [], null);
        $this->setIfExists('function_settings', $data ?? [], null);
        $this->setIfExists('graphics_stored', $data ?? [], null);
        $this->setIfExists('head_up', $data ?? [], null);
        $this->setIfExists('label_length_dots', $data ?? [], null);
        $this->setIfExists('labels_remaining', $data ?? [], null);
        $this->setIfExists('over_temp', $data ?? [], null);
        $this->setIfExists('paper_out', $data ?? [], null);
        $this->setIfExists('partial_format', $data ?? [], null);
        $this->setIfExists('password', $data ?? [], null);
        $this->setIfExists('paused', $data ?? [], null);
        $this->setIfExists('print_mode', $data ?? [], null);
        $this->setIfExists('ribbon_out', $data ?? [], null);
        $this->setIfExists('static_ram', $data ?? [], null);
        $this->setIfExists('thermal_transfer', $data ?? [], null);
        $this->setIfExists('under_temp', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['blocking'] === null) {
            $invalidProperties[] = "'blocking' can't be null";
        }
        if ($this->container['buffer_full'] === null) {
            $invalidProperties[] = "'buffer_full' can't be null";
        }
        if ($this->container['comm_settings'] === null) {
            $invalidProperties[] = "'comm_settings' can't be null";
        }
        if ($this->container['corrupt_ram'] === null) {
            $invalidProperties[] = "'corrupt_ram' can't be null";
        }
        if ($this->container['diagnostic_mode'] === null) {
            $invalidProperties[] = "'diagnostic_mode' can't be null";
        }
        if ($this->container['formats_in_buffer'] === null) {
            $invalidProperties[] = "'formats_in_buffer' can't be null";
        }
        if ($this->container['function_settings'] === null) {
            $invalidProperties[] = "'function_settings' can't be null";
        }
        if ($this->container['graphics_stored'] === null) {
            $invalidProperties[] = "'graphics_stored' can't be null";
        }
        if ($this->container['head_up'] === null) {
            $invalidProperties[] = "'head_up' can't be null";
        }
        if ($this->container['label_length_dots'] === null) {
            $invalidProperties[] = "'label_length_dots' can't be null";
        }
        if ($this->container['labels_remaining'] === null) {
            $invalidProperties[] = "'labels_remaining' can't be null";
        }
        if ($this->container['over_temp'] === null) {
            $invalidProperties[] = "'over_temp' can't be null";
        }
        if ($this->container['paper_out'] === null) {
            $invalidProperties[] = "'paper_out' can't be null";
        }
        if ($this->container['partial_format'] === null) {
            $invalidProperties[] = "'partial_format' can't be null";
        }
        if ($this->container['password'] === null) {
            $invalidProperties[] = "'password' can't be null";
        }
        if ($this->container['paused'] === null) {
            $invalidProperties[] = "'paused' can't be null";
        }
        if ($this->container['print_mode'] === null) {
            $invalidProperties[] = "'print_mode' can't be null";
        }
        if ($this->container['ribbon_out'] === null) {
            $invalidProperties[] = "'ribbon_out' can't be null";
        }
        if ($this->container['static_ram'] === null) {
            $invalidProperties[] = "'static_ram' can't be null";
        }
        if ($this->container['thermal_transfer'] === null) {
            $invalidProperties[] = "'thermal_transfer' can't be null";
        }
        if ($this->container['under_temp'] === null) {
            $invalidProperties[] = "'under_temp' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets blocking
     *
     * @return bool
     */
    public function getBlocking()
    {
        return $this->container['blocking'];
    }

    /**
     * Sets blocking
     *
     * @param bool $blocking True when any condition stops printing
     *
     * @return self
     */
    public function setBlocking($blocking)
    {
        if (is_null($blocking)) {
            throw new \InvalidArgumentException('non-nullable blocking cannot be null');
        }
        $this->container['blocking'] = $blocking;

        return $this;
    }

    /**
     * Gets buffer_full
     *
     * @return bool
     */
    public function getBufferFull()
    {
        return $this->container['buffer_full'];
    }

    /**
     * Sets buffer_full
     *
     * @param bool $buffer_full buffer_full
     *
     * @return self
     */
    public function setBufferFull($buffer_full)
    {
        if (is_null($buffer_full)) {
            throw new \InvalidArgumentException('non-nullable buffer_full cannot be null');
        }
        $this->container['buffer_full'] = $buffer_full;

        return $this;
    }

    /**
     * Gets comm_settings
     *
     * @return string
     */
    public function getCommSettings()
    {
        return $this->container['comm_settings'];
    }

    /**
     * Sets comm_settings
     *
     * @param string $comm_settings Raw communication-settings code
     *
     * @return self
     */
    public function setCommSettings($comm_settings)
    {
        if (is_null($comm_settings)) {
            throw new \InvalidArgumentException('non-nullable comm_settings cannot be null');
        }
        $this->container['comm_settings'] = $comm_settings;

        return $this;
    }

    /**
     * Gets corrupt_ram
     *
     * @return bool
     */
    public function getCorruptRam()
    {
        return $this->container['corrupt_ram'];
    }

    /**
     * Sets corrupt_ram
     *
     * @param bool $corrupt_ram corrupt_ram
     *
     * @return self
     */
    public function setCorruptRam($corrupt_ram)
    {
        if (is_null($corrupt_ram)) {
            throw new \InvalidArgumentException('non-nullable corrupt_ram cannot be null');
        }
        $this->container['corrupt_ram'] = $corrupt_ram;

        return $this;
    }

    /**
     * Gets diagnostic_mode
     *
     * @return bool
     */
    public function getDiagnosticMode()
    {
        return $this->container['diagnostic_mode'];
    }

    /**
     * Sets diagnostic_mode
     *
     * @param bool $diagnostic_mode diagnostic_mode
     *
     * @return self
     */
    public function setDiagnosticMode($diagnostic_mode)
    {
        if (is_null($diagnostic_mode)) {
            throw new \InvalidArgumentException('non-nullable diagnostic_mode cannot be null');
        }
        $this->container['diagnostic_mode'] = $diagnostic_mode;

        return $this;
    }

    /**
     * Gets formats_in_buffer
     *
     * @return int
     */
    public function getFormatsInBuffer()
    {
        return $this->container['formats_in_buffer'];
    }

    /**
     * Sets formats_in_buffer
     *
     * @param int $formats_in_buffer Jobs waiting in the receive buffer
     *
     * @return self
     */
    public function setFormatsInBuffer($formats_in_buffer)
    {
        if (is_null($formats_in_buffer)) {
            throw new \InvalidArgumentException('non-nullable formats_in_buffer cannot be null');
        }
        $this->container['formats_in_buffer'] = $formats_in_buffer;

        return $this;
    }

    /**
     * Gets function_settings
     *
     * @return string
     */
    public function getFunctionSettings()
    {
        return $this->container['function_settings'];
    }

    /**
     * Sets function_settings
     *
     * @param string $function_settings Raw function-settings code
     *
     * @return self
     */
    public function setFunctionSettings($function_settings)
    {
        if (is_null($function_settings)) {
            throw new \InvalidArgumentException('non-nullable function_settings cannot be null');
        }
        $this->container['function_settings'] = $function_settings;

        return $this;
    }

    /**
     * Gets graphics_stored
     *
     * @return int
     */
    public function getGraphicsStored()
    {
        return $this->container['graphics_stored'];
    }

    /**
     * Sets graphics_stored
     *
     * @param int $graphics_stored graphics_stored
     *
     * @return self
     */
    public function setGraphicsStored($graphics_stored)
    {
        if (is_null($graphics_stored)) {
            throw new \InvalidArgumentException('non-nullable graphics_stored cannot be null');
        }
        $this->container['graphics_stored'] = $graphics_stored;

        return $this;
    }

    /**
     * Gets head_up
     *
     * @return bool
     */
    public function getHeadUp()
    {
        return $this->container['head_up'];
    }

    /**
     * Sets head_up
     *
     * @param bool $head_up head_up
     *
     * @return self
     */
    public function setHeadUp($head_up)
    {
        if (is_null($head_up)) {
            throw new \InvalidArgumentException('non-nullable head_up cannot be null');
        }
        $this->container['head_up'] = $head_up;

        return $this;
    }

    /**
     * Gets label_length_dots
     *
     * @return int
     */
    public function getLabelLengthDots()
    {
        return $this->container['label_length_dots'];
    }

    /**
     * Sets label_length_dots
     *
     * @param int $label_length_dots label_length_dots
     *
     * @return self
     */
    public function setLabelLengthDots($label_length_dots)
    {
        if (is_null($label_length_dots)) {
            throw new \InvalidArgumentException('non-nullable label_length_dots cannot be null');
        }
        $this->container['label_length_dots'] = $label_length_dots;

        return $this;
    }

    /**
     * Gets labels_remaining
     *
     * @return int
     */
    public function getLabelsRemaining()
    {
        return $this->container['labels_remaining'];
    }

    /**
     * Sets labels_remaining
     *
     * @param int $labels_remaining labels_remaining
     *
     * @return self
     */
    public function setLabelsRemaining($labels_remaining)
    {
        if (is_null($labels_remaining)) {
            throw new \InvalidArgumentException('non-nullable labels_remaining cannot be null');
        }
        $this->container['labels_remaining'] = $labels_remaining;

        return $this;
    }

    /**
     * Gets over_temp
     *
     * @return bool
     */
    public function getOverTemp()
    {
        return $this->container['over_temp'];
    }

    /**
     * Sets over_temp
     *
     * @param bool $over_temp over_temp
     *
     * @return self
     */
    public function setOverTemp($over_temp)
    {
        if (is_null($over_temp)) {
            throw new \InvalidArgumentException('non-nullable over_temp cannot be null');
        }
        $this->container['over_temp'] = $over_temp;

        return $this;
    }

    /**
     * Gets paper_out
     *
     * @return bool
     */
    public function getPaperOut()
    {
        return $this->container['paper_out'];
    }

    /**
     * Sets paper_out
     *
     * @param bool $paper_out paper_out
     *
     * @return self
     */
    public function setPaperOut($paper_out)
    {
        if (is_null($paper_out)) {
            throw new \InvalidArgumentException('non-nullable paper_out cannot be null');
        }
        $this->container['paper_out'] = $paper_out;

        return $this;
    }

    /**
     * Gets partial_format
     *
     * @return bool
     */
    public function getPartialFormat()
    {
        return $this->container['partial_format'];
    }

    /**
     * Sets partial_format
     *
     * @param bool $partial_format partial_format
     *
     * @return self
     */
    public function setPartialFormat($partial_format)
    {
        if (is_null($partial_format)) {
            throw new \InvalidArgumentException('non-nullable partial_format cannot be null');
        }
        $this->container['partial_format'] = $partial_format;

        return $this;
    }

    /**
     * Gets password
     *
     * @return string
     */
    public function getPassword()
    {
        return $this->container['password'];
    }

    /**
     * Sets password
     *
     * @param string $password password
     *
     * @return self
     */
    public function setPassword($password)
    {
        if (is_null($password)) {
            throw new \InvalidArgumentException('non-nullable password cannot be null');
        }
        $this->container['password'] = $password;

        return $this;
    }

    /**
     * Gets paused
     *
     * @return bool
     */
    public function getPaused()
    {
        return $this->container['paused'];
    }

    /**
     * Sets paused
     *
     * @param bool $paused paused
     *
     * @return self
     */
    public function setPaused($paused)
    {
        if (is_null($paused)) {
            throw new \InvalidArgumentException('non-nullable paused cannot be null');
        }
        $this->container['paused'] = $paused;

        return $this;
    }

    /**
     * Gets print_mode
     *
     * @return string
     */
    public function getPrintMode()
    {
        return $this->container['print_mode'];
    }

    /**
     * Sets print_mode
     *
     * @param string $print_mode rewind, peel-off, tear-off, cutter or applicator
     *
     * @return self
     */
    public function setPrintMode($print_mode)
    {
        if (is_null($print_mode)) {
            throw new \InvalidArgumentException('non-nullable print_mode cannot be null');
        }
        $this->container['print_mode'] = $print_mode;

        return $this;
    }

    /**
     * Gets ribbon_out
     *
     * @return bool
     */
    public function getRibbonOut()
    {
        return $this->container['ribbon_out'];
    }

    /**
     * Sets ribbon_out
     *
     * @param bool $ribbon_out ribbon_out
     *
     * @return self
     */
    public function setRibbonOut($ribbon_out)
    {
        if (is_null($ribbon_out)) {
            throw new \InvalidArgumentException('non-nullable ribbon_out cannot be null');
        }
        $this->container['ribbon_out'] = $ribbon_out;

        return $this;
    }

    /**
     * Gets static_ram
     *
     * @return bool
     */
    public function getStaticRam()
    {
        return $this->container['static_ram'];
    }

    /**
     * Sets static_ram
     *
     * @param bool $static_ram static_ram
     *
     * @return self
     */
    public function setStaticRam($static_ram)
    {
        if (is_null($static_ram)) {
            throw new \InvalidArgumentException('non-nullable static_ram cannot be null');
        }
        $this->container['static_ram'] = $static_ram;

        return $this;
    }

    /**
     * Gets thermal_transfer
     *
     * @return bool
     */
    public function getThermalTransfer()
    {
        return $this->container['thermal_transfer'];
    }

    /**
     * Sets thermal_transfer
     *
     * @param bool $thermal_transfer thermal_transfer
     *
     * @return self
     */
    public function setThermalTransfer($thermal_transfer)
    {
        if (is_null($thermal_transfer)) {
            throw new \InvalidArgumentException('non-nullable thermal_transfer cannot be null');
        }
        $this->container['thermal_transfer'] = $thermal_transfer;

        return $this;
    }

    /**
     * Gets under_temp
     *
     * @return bool
     */
    public function getUnderTemp()
    {
        return $this->container['under_temp'];
    }

    /**
     * Sets under_temp
     *
     * @param bool $under_temp under_temp
     *
     * @return self
     */
    public function setUnderTemp($under_temp)
    {
        if (is_null($under_temp)) {
            throw new \InvalidArgumentException('non-nullable under_temp cannot be null');
        }
        $this->container['under_temp'] = $under_temp;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


