<?php
/**
 * PrinterBody
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  StripyHorse
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace StripyHorse\Model;

use \ArrayAccess;
use \StripyHorse\ObjectSerializer;

/**
 * PrinterBody Class Doc Comment
 *
 * @category Class
 * @package  StripyHorse
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PrinterBody implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'PrinterBody';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'anonymize' => 'bool',
        'created_at' => '\DateTime',
        'dpmm' => 'int',
        'expires_at' => '\DateTime',
        'height_mm' => 'float',
        'id' => 'string',
        'ingest_url' => 'string',
        'mode' => 'string',
        'name' => 'string',
        'state' => '\StripyHorse\Model\StatusSnapshot',
        'tcp' => '\StripyHorse\Model\PrinterBodyTCPStruct',
        'webhook_secret' => 'string',
        'webhook_url' => 'string',
        'width_mm' => 'float'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'anonymize' => null,
        'created_at' => 'date-time',
        'dpmm' => 'int64',
        'expires_at' => 'date-time',
        'height_mm' => 'double',
        'id' => null,
        'ingest_url' => null,
        'mode' => null,
        'name' => null,
        'state' => null,
        'tcp' => null,
        'webhook_secret' => null,
        'webhook_url' => null,
        'width_mm' => 'double'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'anonymize' => false,
        'created_at' => false,
        'dpmm' => false,
        'expires_at' => false,
        'height_mm' => false,
        'id' => false,
        'ingest_url' => false,
        'mode' => false,
        'name' => false,
        'state' => false,
        'tcp' => false,
        'webhook_secret' => false,
        'webhook_url' => false,
        'width_mm' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'anonymize' => 'anonymize',
        'created_at' => 'createdAt',
        'dpmm' => 'dpmm',
        'expires_at' => 'expiresAt',
        'height_mm' => 'heightMm',
        'id' => 'id',
        'ingest_url' => 'ingestUrl',
        'mode' => 'mode',
        'name' => 'name',
        'state' => 'state',
        'tcp' => 'tcp',
        'webhook_secret' => 'webhookSecret',
        'webhook_url' => 'webhookUrl',
        'width_mm' => 'widthMm'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'anonymize' => 'setAnonymize',
        'created_at' => 'setCreatedAt',
        'dpmm' => 'setDpmm',
        'expires_at' => 'setExpiresAt',
        'height_mm' => 'setHeightMm',
        'id' => 'setId',
        'ingest_url' => 'setIngestUrl',
        'mode' => 'setMode',
        'name' => 'setName',
        'state' => 'setState',
        'tcp' => 'setTcp',
        'webhook_secret' => 'setWebhookSecret',
        'webhook_url' => 'setWebhookUrl',
        'width_mm' => 'setWidthMm'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'anonymize' => 'getAnonymize',
        'created_at' => 'getCreatedAt',
        'dpmm' => 'getDpmm',
        'expires_at' => 'getExpiresAt',
        'height_mm' => 'getHeightMm',
        'id' => 'getId',
        'ingest_url' => 'getIngestUrl',
        'mode' => 'getMode',
        'name' => 'getName',
        'state' => 'getState',
        'tcp' => 'getTcp',
        'webhook_secret' => 'getWebhookSecret',
        'webhook_url' => 'getWebhookUrl',
        'width_mm' => 'getWidthMm'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const MODE_EPHEMERAL = 'ephemeral';
    public const MODE_PERSISTENT = 'persistent';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getModeAllowableValues()
    {
        return [
            self::MODE_EPHEMERAL,
            self::MODE_PERSISTENT,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('anonymize', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('dpmm', $data ?? [], null);
        $this->setIfExists('expires_at', $data ?? [], null);
        $this->setIfExists('height_mm', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('ingest_url', $data ?? [], null);
        $this->setIfExists('mode', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('state', $data ?? [], null);
        $this->setIfExists('tcp', $data ?? [], null);
        $this->setIfExists('webhook_secret', $data ?? [], null);
        $this->setIfExists('webhook_url', $data ?? [], null);
        $this->setIfExists('width_mm', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['anonymize'] === null) {
            $invalidProperties[] = "'anonymize' can't be null";
        }
        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        if ($this->container['dpmm'] === null) {
            $invalidProperties[] = "'dpmm' can't be null";
        }
        if ($this->container['height_mm'] === null) {
            $invalidProperties[] = "'height_mm' can't be null";
        }
        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['mode'] === null) {
            $invalidProperties[] = "'mode' can't be null";
        }
        $allowedValues = $this->getModeAllowableValues();
        if (!is_null($this->container['mode']) && !in_array($this->container['mode'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'mode', must be one of '%s'",
                $this->container['mode'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['tcp'] === null) {
            $invalidProperties[] = "'tcp' can't be null";
        }
        if ($this->container['width_mm'] === null) {
            $invalidProperties[] = "'width_mm' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets anonymize
     *
     * @return bool
     */
    public function getAnonymize()
    {
        return $this->container['anonymize'];
    }

    /**
     * Sets anonymize
     *
     * @param bool $anonymize When true, PII is masked and graphics stripped from every captured frame
     *
     * @return self
     */
    public function setAnonymize($anonymize)
    {
        if (is_null($anonymize)) {
            throw new \InvalidArgumentException('non-nullable anonymize cannot be null');
        }
        $this->container['anonymize'] = $anonymize;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets dpmm
     *
     * @return int
     */
    public function getDpmm()
    {
        return $this->container['dpmm'];
    }

    /**
     * Sets dpmm
     *
     * @param int $dpmm dpmm
     *
     * @return self
     */
    public function setDpmm($dpmm)
    {
        if (is_null($dpmm)) {
            throw new \InvalidArgumentException('non-nullable dpmm cannot be null');
        }
        $this->container['dpmm'] = $dpmm;

        return $this;
    }

    /**
     * Gets expires_at
     *
     * @return \DateTime|null
     */
    public function getExpiresAt()
    {
        return $this->container['expires_at'];
    }

    /**
     * Sets expires_at
     *
     * @param \DateTime|null $expires_at expires_at
     *
     * @return self
     */
    public function setExpiresAt($expires_at)
    {
        if (is_null($expires_at)) {
            throw new \InvalidArgumentException('non-nullable expires_at cannot be null');
        }
        $this->container['expires_at'] = $expires_at;

        return $this;
    }

    /**
     * Gets height_mm
     *
     * @return float
     */
    public function getHeightMm()
    {
        return $this->container['height_mm'];
    }

    /**
     * Sets height_mm
     *
     * @param float $height_mm height_mm
     *
     * @return self
     */
    public function setHeightMm($height_mm)
    {
        if (is_null($height_mm)) {
            throw new \InvalidArgumentException('non-nullable height_mm cannot be null');
        }
        $this->container['height_mm'] = $height_mm;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets ingest_url
     *
     * @return string|null
     */
    public function getIngestUrl()
    {
        return $this->container['ingest_url'];
    }

    /**
     * Sets ingest_url
     *
     * @param string|null $ingest_url HTTPS print capability URL. Only returned on creation.
     *
     * @return self
     */
    public function setIngestUrl($ingest_url)
    {
        if (is_null($ingest_url)) {
            throw new \InvalidArgumentException('non-nullable ingest_url cannot be null');
        }
        $this->container['ingest_url'] = $ingest_url;

        return $this;
    }

    /**
     * Gets mode
     *
     * @return string
     */
    public function getMode()
    {
        return $this->container['mode'];
    }

    /**
     * Sets mode
     *
     * @param string $mode mode
     *
     * @return self
     */
    public function setMode($mode)
    {
        if (is_null($mode)) {
            throw new \InvalidArgumentException('non-nullable mode cannot be null');
        }
        $allowedValues = $this->getModeAllowableValues();
        if (!in_array($mode, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'mode', must be one of '%s'",
                    $mode,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['mode'] = $mode;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets state
     *
     * @return \StripyHorse\Model\StatusSnapshot|null
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     *
     * @param \StripyHorse\Model\StatusSnapshot|null $state state
     *
     * @return self
     */
    public function setState($state)
    {
        if (is_null($state)) {
            throw new \InvalidArgumentException('non-nullable state cannot be null');
        }
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets tcp
     *
     * @return \StripyHorse\Model\PrinterBodyTCPStruct
     */
    public function getTcp()
    {
        return $this->container['tcp'];
    }

    /**
     * Sets tcp
     *
     * @param \StripyHorse\Model\PrinterBodyTCPStruct $tcp tcp
     *
     * @return self
     */
    public function setTcp($tcp)
    {
        if (is_null($tcp)) {
            throw new \InvalidArgumentException('non-nullable tcp cannot be null');
        }
        $this->container['tcp'] = $tcp;

        return $this;
    }

    /**
     * Gets webhook_secret
     *
     * @return string|null
     */
    public function getWebhookSecret()
    {
        return $this->container['webhook_secret'];
    }

    /**
     * Sets webhook_secret
     *
     * @param string|null $webhook_secret HMAC-SHA256 key for X-Stripy-Horse-Signature. Only returned on creation.
     *
     * @return self
     */
    public function setWebhookSecret($webhook_secret)
    {
        if (is_null($webhook_secret)) {
            throw new \InvalidArgumentException('non-nullable webhook_secret cannot be null');
        }
        $this->container['webhook_secret'] = $webhook_secret;

        return $this;
    }

    /**
     * Gets webhook_url
     *
     * @return string|null
     */
    public function getWebhookUrl()
    {
        return $this->container['webhook_url'];
    }

    /**
     * Sets webhook_url
     *
     * @param string|null $webhook_url webhook_url
     *
     * @return self
     */
    public function setWebhookUrl($webhook_url)
    {
        if (is_null($webhook_url)) {
            throw new \InvalidArgumentException('non-nullable webhook_url cannot be null');
        }
        $this->container['webhook_url'] = $webhook_url;

        return $this;
    }

    /**
     * Gets width_mm
     *
     * @return float
     */
    public function getWidthMm()
    {
        return $this->container['width_mm'];
    }

    /**
     * Sets width_mm
     *
     * @param float $width_mm width_mm
     *
     * @return self
     */
    public function setWidthMm($width_mm)
    {
        if (is_null($width_mm)) {
            throw new \InvalidArgumentException('non-nullable width_mm cannot be null');
        }
        $this->container['width_mm'] = $width_mm;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


