<?php
/**
 * StatusSnapshot
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  StripyHorse
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace StripyHorse\Model;

use \ArrayAccess;
use \StripyHorse\ObjectSerializer;

/**
 * StatusSnapshot Class Doc Comment
 *
 * @category Class
 * @package  StripyHorse
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class StatusSnapshot implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'StatusSnapshot';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'darkness' => 'string',
        'faults' => '\StripyHorse\Model\Faults',
        'formats_in_buffer' => 'int',
        'friendly_name' => 'string',
        'label_length_dots' => 'int',
        'odometer' => 'int',
        'queue' => '\StripyHorse\Model\HeldJob[]',
        'speed_ips' => 'string',
        'tear_off' => 'string',
        'width_dots' => 'int'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'darkness' => null,
        'faults' => null,
        'formats_in_buffer' => 'int64',
        'friendly_name' => null,
        'label_length_dots' => 'int64',
        'odometer' => 'int64',
        'queue' => null,
        'speed_ips' => null,
        'tear_off' => null,
        'width_dots' => 'int64'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'darkness' => false,
        'faults' => false,
        'formats_in_buffer' => false,
        'friendly_name' => false,
        'label_length_dots' => false,
        'odometer' => false,
        'queue' => true,
        'speed_ips' => false,
        'tear_off' => false,
        'width_dots' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'darkness' => 'darkness',
        'faults' => 'faults',
        'formats_in_buffer' => 'formatsInBuffer',
        'friendly_name' => 'friendlyName',
        'label_length_dots' => 'labelLengthDots',
        'odometer' => 'odometer',
        'queue' => 'queue',
        'speed_ips' => 'speedIps',
        'tear_off' => 'tearOff',
        'width_dots' => 'widthDots'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'darkness' => 'setDarkness',
        'faults' => 'setFaults',
        'formats_in_buffer' => 'setFormatsInBuffer',
        'friendly_name' => 'setFriendlyName',
        'label_length_dots' => 'setLabelLengthDots',
        'odometer' => 'setOdometer',
        'queue' => 'setQueue',
        'speed_ips' => 'setSpeedIps',
        'tear_off' => 'setTearOff',
        'width_dots' => 'setWidthDots'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'darkness' => 'getDarkness',
        'faults' => 'getFaults',
        'formats_in_buffer' => 'getFormatsInBuffer',
        'friendly_name' => 'getFriendlyName',
        'label_length_dots' => 'getLabelLengthDots',
        'odometer' => 'getOdometer',
        'queue' => 'getQueue',
        'speed_ips' => 'getSpeedIps',
        'tear_off' => 'getTearOff',
        'width_dots' => 'getWidthDots'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('darkness', $data ?? [], null);
        $this->setIfExists('faults', $data ?? [], null);
        $this->setIfExists('formats_in_buffer', $data ?? [], null);
        $this->setIfExists('friendly_name', $data ?? [], null);
        $this->setIfExists('label_length_dots', $data ?? [], null);
        $this->setIfExists('odometer', $data ?? [], null);
        $this->setIfExists('queue', $data ?? [], null);
        $this->setIfExists('speed_ips', $data ?? [], null);
        $this->setIfExists('tear_off', $data ?? [], null);
        $this->setIfExists('width_dots', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['darkness'] === null) {
            $invalidProperties[] = "'darkness' can't be null";
        }
        if ($this->container['faults'] === null) {
            $invalidProperties[] = "'faults' can't be null";
        }
        if ($this->container['formats_in_buffer'] === null) {
            $invalidProperties[] = "'formats_in_buffer' can't be null";
        }
        if ($this->container['friendly_name'] === null) {
            $invalidProperties[] = "'friendly_name' can't be null";
        }
        if ($this->container['label_length_dots'] === null) {
            $invalidProperties[] = "'label_length_dots' can't be null";
        }
        if ($this->container['odometer'] === null) {
            $invalidProperties[] = "'odometer' can't be null";
        }
        if ($this->container['queue'] === null && !$this->isNullableSetToNull('queue')) {
            $invalidProperties[] = "'queue' is required";
        }
        if ($this->container['speed_ips'] === null) {
            $invalidProperties[] = "'speed_ips' can't be null";
        }
        if ($this->container['tear_off'] === null) {
            $invalidProperties[] = "'tear_off' can't be null";
        }
        if ($this->container['width_dots'] === null) {
            $invalidProperties[] = "'width_dots' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets darkness
     *
     * @return string
     */
    public function getDarkness()
    {
        return $this->container['darkness'];
    }

    /**
     * Sets darkness
     *
     * @param string $darkness print.tone setting, e.g. 20.0
     *
     * @return self
     */
    public function setDarkness($darkness)
    {
        if (is_null($darkness)) {
            throw new \InvalidArgumentException('non-nullable darkness cannot be null');
        }
        $this->container['darkness'] = $darkness;

        return $this;
    }

    /**
     * Gets faults
     *
     * @return \StripyHorse\Model\Faults
     */
    public function getFaults()
    {
        return $this->container['faults'];
    }

    /**
     * Sets faults
     *
     * @param \StripyHorse\Model\Faults $faults faults
     *
     * @return self
     */
    public function setFaults($faults)
    {
        if (is_null($faults)) {
            throw new \InvalidArgumentException('non-nullable faults cannot be null');
        }
        $this->container['faults'] = $faults;

        return $this;
    }

    /**
     * Gets formats_in_buffer
     *
     * @return int
     */
    public function getFormatsInBuffer()
    {
        return $this->container['formats_in_buffer'];
    }

    /**
     * Sets formats_in_buffer
     *
     * @param int $formats_in_buffer formats_in_buffer
     *
     * @return self
     */
    public function setFormatsInBuffer($formats_in_buffer)
    {
        if (is_null($formats_in_buffer)) {
            throw new \InvalidArgumentException('non-nullable formats_in_buffer cannot be null');
        }
        $this->container['formats_in_buffer'] = $formats_in_buffer;

        return $this;
    }

    /**
     * Gets friendly_name
     *
     * @return string
     */
    public function getFriendlyName()
    {
        return $this->container['friendly_name'];
    }

    /**
     * Sets friendly_name
     *
     * @param string $friendly_name device.friendly_name override; empty means unset
     *
     * @return self
     */
    public function setFriendlyName($friendly_name)
    {
        if (is_null($friendly_name)) {
            throw new \InvalidArgumentException('non-nullable friendly_name cannot be null');
        }
        $this->container['friendly_name'] = $friendly_name;

        return $this;
    }

    /**
     * Gets label_length_dots
     *
     * @return int
     */
    public function getLabelLengthDots()
    {
        return $this->container['label_length_dots'];
    }

    /**
     * Sets label_length_dots
     *
     * @param int $label_length_dots label_length_dots
     *
     * @return self
     */
    public function setLabelLengthDots($label_length_dots)
    {
        if (is_null($label_length_dots)) {
            throw new \InvalidArgumentException('non-nullable label_length_dots cannot be null');
        }
        $this->container['label_length_dots'] = $label_length_dots;

        return $this;
    }

    /**
     * Gets odometer
     *
     * @return int
     */
    public function getOdometer()
    {
        return $this->container['odometer'];
    }

    /**
     * Sets odometer
     *
     * @param int $odometer odometer
     *
     * @return self
     */
    public function setOdometer($odometer)
    {
        if (is_null($odometer)) {
            throw new \InvalidArgumentException('non-nullable odometer cannot be null');
        }
        $this->container['odometer'] = $odometer;

        return $this;
    }

    /**
     * Gets queue
     *
     * @return \StripyHorse\Model\HeldJob[]|null
     */
    public function getQueue()
    {
        return $this->container['queue'];
    }

    /**
     * Sets queue
     *
     * @param \StripyHorse\Model\HeldJob[]|null $queue queue
     *
     * @return self
     */
    public function setQueue($queue)
    {
        if (is_null($queue)) {
            array_push($this->openAPINullablesSetToNull, 'queue');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('queue', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['queue'] = $queue;

        return $this;
    }

    /**
     * Gets speed_ips
     *
     * @return string
     */
    public function getSpeedIps()
    {
        return $this->container['speed_ips'];
    }

    /**
     * Sets speed_ips
     *
     * @param string $speed_ips media.speed setting, inches/second
     *
     * @return self
     */
    public function setSpeedIps($speed_ips)
    {
        if (is_null($speed_ips)) {
            throw new \InvalidArgumentException('non-nullable speed_ips cannot be null');
        }
        $this->container['speed_ips'] = $speed_ips;

        return $this;
    }

    /**
     * Gets tear_off
     *
     * @return string
     */
    public function getTearOff()
    {
        return $this->container['tear_off'];
    }

    /**
     * Sets tear_off
     *
     * @param string $tear_off ezpl.tear_off setting, dots
     *
     * @return self
     */
    public function setTearOff($tear_off)
    {
        if (is_null($tear_off)) {
            throw new \InvalidArgumentException('non-nullable tear_off cannot be null');
        }
        $this->container['tear_off'] = $tear_off;

        return $this;
    }

    /**
     * Gets width_dots
     *
     * @return int
     */
    public function getWidthDots()
    {
        return $this->container['width_dots'];
    }

    /**
     * Sets width_dots
     *
     * @param int $width_dots width_dots
     *
     * @return self
     */
    public function setWidthDots($width_dots)
    {
        if (is_null($width_dots)) {
            throw new \InvalidArgumentException('non-nullable width_dots cannot be null');
        }
        $this->container['width_dots'] = $width_dots;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


