<?php
/**
 * HostStatusTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  StripyHorse
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.26.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace StripyHorse\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * HostStatusTest Class Doc Comment
 *
 * @category    Class
 * @description HostStatus
 * @package     StripyHorse
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class HostStatusTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "HostStatus"
     */
    public function testHostStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "blocking"
     */
    public function testPropertyBlocking()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "buffer_full"
     */
    public function testPropertyBufferFull()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "comm_settings"
     */
    public function testPropertyCommSettings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "corrupt_ram"
     */
    public function testPropertyCorruptRam()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "diagnostic_mode"
     */
    public function testPropertyDiagnosticMode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "formats_in_buffer"
     */
    public function testPropertyFormatsInBuffer()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "function_settings"
     */
    public function testPropertyFunctionSettings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "graphics_stored"
     */
    public function testPropertyGraphicsStored()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "head_up"
     */
    public function testPropertyHeadUp()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "label_length_dots"
     */
    public function testPropertyLabelLengthDots()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "labels_remaining"
     */
    public function testPropertyLabelsRemaining()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "over_temp"
     */
    public function testPropertyOverTemp()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "paper_out"
     */
    public function testPropertyPaperOut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "partial_format"
     */
    public function testPropertyPartialFormat()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "password"
     */
    public function testPropertyPassword()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "paused"
     */
    public function testPropertyPaused()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "print_mode"
     */
    public function testPropertyPrintMode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ribbon_out"
     */
    public function testPropertyRibbonOut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "static_ram"
     */
    public function testPropertyStaticRam()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "thermal_transfer"
     */
    public function testPropertyThermalTransfer()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "under_temp"
     */
    public function testPropertyUnderTemp()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
