<?php
/**
 * HtmlInputBodyTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  StripyHorse
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace StripyHorse\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * HtmlInputBodyTest Class Doc Comment
 *
 * @category    Class
 * @description HtmlInputBody
 * @package     StripyHorse
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class HtmlInputBodyTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "HtmlInputBody"
     */
    public function testHtmlInputBody()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "compression"
     */
    public function testPropertyCompression()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dpmm"
     */
    public function testPropertyDpmm()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "height_mm"
     */
    public function testPropertyHeightMm()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "html"
     */
    public function testPropertyHtml()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "preset"
     */
    public function testPropertyPreset()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "threshold"
     */
    public function testPropertyThreshold()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "width_mm"
     */
    public function testPropertyWidthMm()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
