<?php
/**
 * ConvertApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  StripyHorse
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ben@stripyhorse.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace StripyHorse\Test\Api;

use \StripyHorse\Configuration;
use \StripyHorse\ApiException;
use \StripyHorse\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ConvertApiTest Class Doc Comment
 *
 * @category Class
 * @package  StripyHorse
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ConvertApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for convertBatch
     *
     * Convert many documents in one request, results streamed.
     *
     */
    public function testConvertBatch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for convertDocument
     *
     * Convert a PDF or image to ZPL.
     *
     */
    public function testConvertDocument()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for convertHtml
     *
     * Convert an HTML label design to ZPL.
     *
     */
    public function testConvertHtml()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for convertZplToHtml
     *
     * Decompile ZPL into editable HTML.
     *
     */
    public function testConvertZplToHtml()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for rasterizeUnicode
     *
     * Make Unicode ZPL printable on any Zebra.
     *
     */
    public function testRasterizeUnicode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for stampZpl
     *
     * Stamp an image onto ZPL labels.
     *
     */
    public function testStampZpl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for voidZpl
     *
     * Stamp ZPL as void / do-not-ship.
     *
     */
    public function testVoidZpl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
