<?php
/**
 * SimulatorApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  StripyHorse
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Stripy Horse API
 *
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace StripyHorse\Test\Api;

use \StripyHorse\Configuration;
use \StripyHorse\ApiException;
use \StripyHorse\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SimulatorApiTest Class Doc Comment
 *
 * @category Class
 * @package  StripyHorse
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SimulatorApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for clearJobs
     *
     * Delete all captured jobs.
     *
     */
    public function testClearJobs()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createPrinter
     *
     * Create a virtual printer.
     *
     */
    public function testCreatePrinter()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deletePrinter
     *
     * Delete a printer and its captured jobs.
     *
     */
    public function testDeletePrinter()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getJob
     *
     * Get one job including its raw ZPL.
     *
     */
    public function testGetJob()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getJobLabel
     *
     * Get one rendered label as a PNG.
     *
     */
    public function testGetJobLabel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPrinter
     *
     * Get a printer with live state.
     *
     */
    public function testGetPrinter()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listJobs
     *
     * List captured jobs, newest first.
     *
     */
    public function testListJobs()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listPrinters
     *
     * List your printers.
     *
     */
    public function testListPrinters()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for resetPrinter
     *
     * Clear all faults and flush held jobs.
     *
     */
    public function testResetPrinter()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for setPrinterFaults
     *
     * Inject or clear fault conditions.
     *
     */
    public function testSetPrinterFaults()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updatePrinter
     *
     * Rename a printer or set its webhook URL.
     *
     */
    public function testUpdatePrinter()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
